/*
###############################################################
#  Generated by:      Cadence Innovus 17.11-s080_1
#  OS:                Linux x86_64(Host ID localhost.localdomain)
#  Generated on:      Sat Nov 20 20:45:43 2021
#  Design:            IIR_filter
#  Command:           saveNetlist IIR_filter.v
###############################################################
*/
/////////////////////////////////////////////////////////////
// Created by: Synopsys DC Expert(TM) in wire load mode
// Version   : O-2018.06-SP4
// Date      : Sat Nov 20 19:34:47 2021
/////////////////////////////////////////////////////////////
module IIR_filter (
	CLK, 
	RST_n, 
	H0, 
	H1, 
	H2, 
	H3, 
	VIN, 
	VOUT, 
	DIN, 
	DOUT);
   input CLK;
   input RST_n;
   input [8:0] H0;
   input [8:0] H1;
   input [8:0] H2;
   input [8:0] H3;
   input VIN;
   output VOUT;
   input [8:0] DIN;
   output [8:0] DOUT;

   // Internal wires
   wire FE_OFN4_mult_161_n262;
   wire FE_OFN3_mult_172_n262;
   wire FE_OFN2_mult_161_n251;
   wire FE_OFN1_delayRegOut_1;
   wire FE_OFN0_mult_172_n251;
   wire FE_DBTN4_RST_n;
   wire FE_DBTN3_delayRegOut_0;
   wire FE_DBTN2_delayRegOut_3;
   wire FE_DBTN1_delayRegOut_5;
   wire FE_DBTN0_delayRegOut_7;
   wire N12;
   wire N14;
   wire n7;
   wire n8;
   wire n9;
   wire n11;
   wire n12;
   wire n13;
   wire n14;
   wire n15;
   wire n17;
   wire n18;
   wire delayReg_n8;
   wire delayReg_n7;
   wire delayReg_n6;
   wire delayReg_n5;
   wire delayReg_n4;
   wire delayReg_n3;
   wire delayReg_n2;
   wire delayReg_n1;
   wire delayReg_n19;
   wire delayReg_n18;
   wire delayReg_n17;
   wire delayReg_n16;
   wire delayReg_n15;
   wire delayReg_n14;
   wire delayReg_n13;
   wire delayReg_n12;
   wire delayReg_n11;
   wire delayReg_n10;
   wire DoutReg_n29;
   wire DoutReg_n28;
   wire DoutReg_n27;
   wire DoutReg_n26;
   wire DoutReg_n25;
   wire DoutReg_n24;
   wire DoutReg_n23;
   wire DoutReg_n22;
   wire DoutReg_n21;
   wire DoutReg_n20;
   wire DoutReg_n8;
   wire DoutReg_n7;
   wire DoutReg_n6;
   wire DoutReg_n5;
   wire DoutReg_n4;
   wire DoutReg_n3;
   wire DoutReg_n2;
   wire DoutReg_n1;
   wire chk_ovf_fb_n1;
   wire chk_ovf_fb_n3;
   wire chk_ovf_fb_n2;
   wire chk_ovf_ff_n5;
   wire chk_ovf_ff_n4;
   wire chk_ovf_ff_n1;
   wire chk_ovf_w_n2;
   wire chk_ovf_w_n1;
   wire chk_ovf_w_n12;
   wire chk_ovf_w_n11;
   wire chk_ovf_w_n10;
   wire chk_ovf_w_n9;
   wire chk_ovf_w_n8;
   wire chk_ovf_w_n7;
   wire chk_ovf_w_n6;
   wire chk_ovf_w_n5;
   wire chk_ovf_w_n4;
   wire chk_ovf_w_n3;
   wire chk_ovf_multb0_n5;
   wire chk_ovf_multb0_n4;
   wire chk_ovf_multb0_n1;
   wire chk_ovf_douts_n8;
   wire chk_ovf_douts_n7;
   wire chk_ovf_douts_n6;
   wire chk_ovf_douts_n5;
   wire chk_ovf_douts_n4;
   wire chk_ovf_douts_n3;
   wire chk_ovf_douts_n2;
   wire chk_ovf_douts_n1;
   wire chk_ovf_douts_n12;
   wire chk_ovf_douts_n11;
   wire chk_ovf_douts_n10;
   wire chk_ovf_douts_n9;
   wire add_177_n1;
   wire sub_169_n9;
   wire sub_169_n8;
   wire sub_169_n7;
   wire sub_169_n6;
   wire sub_169_n5;
   wire sub_169_n4;
   wire sub_169_n3;
   wire sub_169_n2;
   wire sub_169_n1;
   wire mult_162_n282;
   wire mult_162_n281;
   wire mult_162_n280;
   wire mult_162_n279;
   wire mult_162_n278;
   wire mult_162_n277;
   wire mult_162_n276;
   wire mult_162_n275;
   wire mult_162_n274;
   wire mult_162_n273;
   wire mult_162_n272;
   wire mult_162_n271;
   wire mult_162_n270;
   wire mult_162_n269;
   wire mult_162_n268;
   wire mult_162_n267;
   wire mult_162_n266;
   wire mult_162_n265;
   wire mult_162_n264;
   wire mult_162_n263;
   wire mult_162_n262;
   wire mult_162_n261;
   wire mult_162_n260;
   wire mult_162_n259;
   wire mult_162_n258;
   wire mult_162_n257;
   wire mult_162_n256;
   wire mult_162_n255;
   wire mult_162_n254;
   wire mult_162_n253;
   wire mult_162_n252;
   wire mult_162_n251;
   wire mult_162_n250;
   wire mult_162_n249;
   wire mult_162_n248;
   wire mult_162_n247;
   wire mult_162_n246;
   wire mult_162_n245;
   wire mult_162_n244;
   wire mult_162_n243;
   wire mult_162_n242;
   wire mult_162_n241;
   wire mult_162_n240;
   wire mult_162_n239;
   wire mult_162_n238;
   wire mult_162_n237;
   wire mult_162_n236;
   wire mult_162_n235;
   wire mult_162_n234;
   wire mult_162_n233;
   wire mult_162_n232;
   wire mult_162_n231;
   wire mult_162_n230;
   wire mult_162_n229;
   wire mult_162_n228;
   wire mult_162_n227;
   wire mult_162_n226;
   wire mult_162_n225;
   wire mult_162_n223;
   wire mult_162_n222;
   wire mult_162_n221;
   wire mult_162_n220;
   wire mult_162_n218;
   wire mult_162_n217;
   wire mult_162_n216;
   wire mult_162_n214;
   wire mult_162_n213;
   wire mult_162_n212;
   wire mult_162_n211;
   wire mult_162_n209;
   wire mult_162_n208;
   wire mult_162_n207;
   wire mult_162_product_6_;
   wire mult_162_product_5_;
   wire mult_162_product_4_;
   wire mult_162_product_3_;
   wire mult_162_product_2_;
   wire mult_162_product_1_;
   wire mult_162_n102;
   wire mult_162_n101;
   wire mult_162_n100;
   wire mult_162_n99;
   wire mult_162_n98;
   wire mult_162_n95;
   wire mult_162_n94;
   wire mult_162_n93;
   wire mult_162_n92;
   wire mult_162_n91;
   wire mult_162_n89;
   wire mult_162_n88;
   wire mult_162_n87;
   wire mult_162_n86;
   wire mult_162_n85;
   wire mult_162_n84;
   wire mult_162_n83;
   wire mult_162_n82;
   wire mult_162_n80;
   wire mult_162_n79;
   wire mult_162_n77;
   wire mult_162_n76;
   wire mult_162_n75;
   wire mult_162_n74;
   wire mult_162_n70;
   wire mult_162_n69;
   wire mult_162_n56;
   wire mult_162_n55;
   wire mult_162_n54;
   wire mult_162_n53;
   wire mult_162_n52;
   wire mult_162_n51;
   wire mult_162_n50;
   wire mult_162_n49;
   wire mult_162_n48;
   wire mult_162_n47;
   wire mult_162_n46;
   wire mult_162_n45;
   wire mult_162_n44;
   wire mult_162_n43;
   wire mult_162_n42;
   wire mult_162_n41;
   wire mult_162_n40;
   wire mult_162_n39;
   wire mult_162_n38;
   wire mult_162_n37;
   wire mult_162_n36;
   wire mult_162_n35;
   wire mult_162_n34;
   wire mult_162_n33;
   wire mult_162_n32;
   wire mult_162_n30;
   wire mult_162_n29;
   wire mult_162_n28;
   wire mult_162_n27;
   wire mult_162_n26;
   wire mult_162_n25;
   wire mult_162_n24;
   wire mult_162_n23;
   wire mult_162_n21;
   wire mult_162_n20;
   wire mult_162_n19;
   wire mult_162_n18;
   wire mult_162_n17;
   wire mult_162_n15;
   wire mult_162_n9;
   wire mult_162_n8;
   wire mult_162_n7;
   wire mult_162_n6;
   wire mult_162_n5;
   wire mult_162_n4;
   wire mult_162_n3;
   wire mult_162_n2;
   wire mult_162_n1;
   wire mult_161_n282;
   wire mult_161_n281;
   wire mult_161_n278;
   wire mult_161_n277;
   wire mult_161_n276;
   wire mult_161_n275;
   wire mult_161_n274;
   wire mult_161_n273;
   wire mult_161_n272;
   wire mult_161_n271;
   wire mult_161_n270;
   wire mult_161_n269;
   wire mult_161_n268;
   wire mult_161_n267;
   wire mult_161_n266;
   wire mult_161_n265;
   wire mult_161_n264;
   wire mult_161_n263;
   wire mult_161_n262;
   wire mult_161_n261;
   wire mult_161_n260;
   wire mult_161_n259;
   wire mult_161_n258;
   wire mult_161_n257;
   wire mult_161_n256;
   wire mult_161_n255;
   wire mult_161_n254;
   wire mult_161_n253;
   wire mult_161_n252;
   wire mult_161_n251;
   wire mult_161_n250;
   wire mult_161_n249;
   wire mult_161_n248;
   wire mult_161_n247;
   wire mult_161_n246;
   wire mult_161_n245;
   wire mult_161_n244;
   wire mult_161_n243;
   wire mult_161_n242;
   wire mult_161_n241;
   wire mult_161_n240;
   wire mult_161_n239;
   wire mult_161_n238;
   wire mult_161_n237;
   wire mult_161_n236;
   wire mult_161_n235;
   wire mult_161_n234;
   wire mult_161_n233;
   wire mult_161_n232;
   wire mult_161_n231;
   wire mult_161_n230;
   wire mult_161_n229;
   wire mult_161_n228;
   wire mult_161_n227;
   wire mult_161_n226;
   wire mult_161_n225;
   wire mult_161_n223;
   wire mult_161_n222;
   wire mult_161_n221;
   wire mult_161_n220;
   wire mult_161_n218;
   wire mult_161_n217;
   wire mult_161_n216;
   wire mult_161_n214;
   wire mult_161_n213;
   wire mult_161_n212;
   wire mult_161_n211;
   wire mult_161_n209;
   wire mult_161_n208;
   wire mult_161_n207;
   wire mult_161_product_6_;
   wire mult_161_product_5_;
   wire mult_161_product_4_;
   wire mult_161_product_3_;
   wire mult_161_product_2_;
   wire mult_161_product_1_;
   wire mult_161_n102;
   wire mult_161_n101;
   wire mult_161_n100;
   wire mult_161_n99;
   wire mult_161_n98;
   wire mult_161_n95;
   wire mult_161_n94;
   wire mult_161_n93;
   wire mult_161_n92;
   wire mult_161_n91;
   wire mult_161_n89;
   wire mult_161_n88;
   wire mult_161_n87;
   wire mult_161_n86;
   wire mult_161_n85;
   wire mult_161_n84;
   wire mult_161_n83;
   wire mult_161_n82;
   wire mult_161_n80;
   wire mult_161_n79;
   wire mult_161_n77;
   wire mult_161_n76;
   wire mult_161_n75;
   wire mult_161_n74;
   wire mult_161_n70;
   wire mult_161_n69;
   wire mult_161_n56;
   wire mult_161_n55;
   wire mult_161_n54;
   wire mult_161_n53;
   wire mult_161_n52;
   wire mult_161_n51;
   wire mult_161_n50;
   wire mult_161_n49;
   wire mult_161_n48;
   wire mult_161_n47;
   wire mult_161_n46;
   wire mult_161_n45;
   wire mult_161_n44;
   wire mult_161_n43;
   wire mult_161_n42;
   wire mult_161_n41;
   wire mult_161_n40;
   wire mult_161_n39;
   wire mult_161_n38;
   wire mult_161_n37;
   wire mult_161_n36;
   wire mult_161_n35;
   wire mult_161_n34;
   wire mult_161_n33;
   wire mult_161_n32;
   wire mult_161_n30;
   wire mult_161_n29;
   wire mult_161_n28;
   wire mult_161_n27;
   wire mult_161_n26;
   wire mult_161_n25;
   wire mult_161_n24;
   wire mult_161_n23;
   wire mult_161_n21;
   wire mult_161_n20;
   wire mult_161_n19;
   wire mult_161_n18;
   wire mult_161_n17;
   wire mult_161_n15;
   wire mult_161_n9;
   wire mult_161_n8;
   wire mult_161_n7;
   wire mult_161_n6;
   wire mult_161_n5;
   wire mult_161_n4;
   wire mult_161_n3;
   wire mult_161_n2;
   wire mult_161_n1;
   wire mult_172_n282;
   wire mult_172_n281;
   wire mult_172_n280;
   wire mult_172_n279;
   wire mult_172_n278;
   wire mult_172_n277;
   wire mult_172_n276;
   wire mult_172_n275;
   wire mult_172_n274;
   wire mult_172_n273;
   wire mult_172_n272;
   wire mult_172_n271;
   wire mult_172_n270;
   wire mult_172_n269;
   wire mult_172_n268;
   wire mult_172_n267;
   wire mult_172_n266;
   wire mult_172_n265;
   wire mult_172_n264;
   wire mult_172_n263;
   wire mult_172_n262;
   wire mult_172_n261;
   wire mult_172_n260;
   wire mult_172_n259;
   wire mult_172_n258;
   wire mult_172_n257;
   wire mult_172_n256;
   wire mult_172_n255;
   wire mult_172_n254;
   wire mult_172_n253;
   wire mult_172_n252;
   wire mult_172_n251;
   wire mult_172_n250;
   wire mult_172_n249;
   wire mult_172_n248;
   wire mult_172_n247;
   wire mult_172_n246;
   wire mult_172_n245;
   wire mult_172_n244;
   wire mult_172_n243;
   wire mult_172_n242;
   wire mult_172_n241;
   wire mult_172_n240;
   wire mult_172_n239;
   wire mult_172_n238;
   wire mult_172_n237;
   wire mult_172_n236;
   wire mult_172_n235;
   wire mult_172_n234;
   wire mult_172_n233;
   wire mult_172_n232;
   wire mult_172_n231;
   wire mult_172_n230;
   wire mult_172_n229;
   wire mult_172_n228;
   wire mult_172_n227;
   wire mult_172_n226;
   wire mult_172_n225;
   wire mult_172_n224;
   wire mult_172_n223;
   wire mult_172_n222;
   wire mult_172_n221;
   wire mult_172_n220;
   wire mult_172_n219;
   wire mult_172_n218;
   wire mult_172_n217;
   wire mult_172_n216;
   wire mult_172_n215;
   wire mult_172_n214;
   wire mult_172_n213;
   wire mult_172_n212;
   wire mult_172_n211;
   wire mult_172_n210;
   wire mult_172_n209;
   wire mult_172_n208;
   wire mult_172_n207;
   wire mult_172_product_6_;
   wire mult_172_product_5_;
   wire mult_172_product_4_;
   wire mult_172_product_3_;
   wire mult_172_product_2_;
   wire mult_172_product_1_;
   wire mult_172_n102;
   wire mult_172_n101;
   wire mult_172_n100;
   wire mult_172_n99;
   wire mult_172_n98;
   wire mult_172_n95;
   wire mult_172_n94;
   wire mult_172_n93;
   wire mult_172_n92;
   wire mult_172_n91;
   wire mult_172_n89;
   wire mult_172_n88;
   wire mult_172_n87;
   wire mult_172_n86;
   wire mult_172_n85;
   wire mult_172_n84;
   wire mult_172_n83;
   wire mult_172_n82;
   wire mult_172_n80;
   wire mult_172_n79;
   wire mult_172_n77;
   wire mult_172_n76;
   wire mult_172_n75;
   wire mult_172_n74;
   wire mult_172_n70;
   wire mult_172_n69;
   wire mult_172_n56;
   wire mult_172_n55;
   wire mult_172_n54;
   wire mult_172_n53;
   wire mult_172_n52;
   wire mult_172_n51;
   wire mult_172_n50;
   wire mult_172_n49;
   wire mult_172_n48;
   wire mult_172_n47;
   wire mult_172_n46;
   wire mult_172_n45;
   wire mult_172_n44;
   wire mult_172_n43;
   wire mult_172_n42;
   wire mult_172_n41;
   wire mult_172_n40;
   wire mult_172_n39;
   wire mult_172_n38;
   wire mult_172_n37;
   wire mult_172_n36;
   wire mult_172_n35;
   wire mult_172_n34;
   wire mult_172_n33;
   wire mult_172_n32;
   wire mult_172_n30;
   wire mult_172_n29;
   wire mult_172_n28;
   wire mult_172_n27;
   wire mult_172_n26;
   wire mult_172_n25;
   wire mult_172_n24;
   wire mult_172_n23;
   wire mult_172_n21;
   wire mult_172_n20;
   wire mult_172_n19;
   wire mult_172_n18;
   wire mult_172_n17;
   wire mult_172_n15;
   wire mult_172_n9;
   wire mult_172_n8;
   wire mult_172_n7;
   wire mult_172_n6;
   wire mult_172_n5;
   wire mult_172_n4;
   wire mult_172_n3;
   wire mult_172_n2;
   wire mult_172_n1;
   wire [7:0] DinRegOut;
   wire [7:0] w_sat;
   wire [7:0] delayRegOut;
   wire [7:0] DOUT_s_sat;
   wire [2:0] current_state;
   wire [15:0] feedback;
   wire [15:0] feedforward;
   wire [7:0] feedback_sat;
   wire [7:0] feedforward_sat;
   wire [7:0] w;
   wire [15:0] multb0;
   wire [7:0] multb0_sat;
   wire [7:0] DOUT_s;
   wire [7:2] add_177_carry;
   wire [7:1] sub_169_carry;

   assign DOUT[0] = 1'b0 ;

   CLKBUF_X2 FE_OFC4_mult_161_n262 (.A(mult_161_n262),
	.Z(FE_OFN4_mult_161_n262));
   CLKBUF_X2 FE_OFC3_mult_172_n262 (.A(mult_172_n262),
	.Z(FE_OFN3_mult_172_n262));
   CLKBUF_X2 FE_OFC2_mult_161_n251 (.A(mult_161_n251),
	.Z(FE_OFN2_mult_161_n251));
   CLKBUF_X2 FE_OFC1_delayRegOut_1 (.A(delayRegOut[1]),
	.Z(FE_OFN1_delayRegOut_1));
   CLKBUF_X2 FE_OFC0_mult_172_n251 (.A(mult_172_n251),
	.Z(FE_OFN0_mult_172_n251));
   OAI21_X1 FE_RC_7_0 (.A(mult_172_n250),
	.B1(mult_172_n219),
	.B2(mult_172_n218),
	.ZN(mult_172_n89));
   AOI21_X1 FE_RC_6_0 (.A(mult_172_n230),
	.B1(mult_172_n216),
	.B2(mult_172_n228),
	.ZN(mult_172_n231));
   AOI21_X1 FE_RC_5_0 (.A(mult_172_n261),
	.B1(FE_OFN0_mult_172_n251),
	.B2(mult_172_n253),
	.ZN(mult_172_n260));
   AOI21_X1 FE_RC_4_0 (.A(mult_172_n272),
	.B1(FE_OFN3_mult_172_n262),
	.B2(mult_172_n264),
	.ZN(mult_172_n271));
   OAI21_X1 FE_RC_3_0 (.A(mult_161_n250),
	.B1(mult_161_n222),
	.B2(mult_161_n221),
	.ZN(mult_161_n89));
   OAI21_X1 FE_RC_2_0 (.A(mult_162_n250),
	.B1(mult_162_n222),
	.B2(mult_162_n221),
	.ZN(mult_162_n89));
   AOI21_X1 FE_RC_1_0 (.A(mult_161_n230),
	.B1(FE_DBTN3_delayRegOut_0),
	.B2(mult_161_n228),
	.ZN(mult_161_n231));
   AOI21_X1 FE_RC_0_0 (.A(mult_162_n272),
	.B1(mult_162_n262),
	.B2(mult_162_n264),
	.ZN(mult_162_n271));
   INV_X1 FE_DBTC4_RST_n (.A(RST_n),
	.ZN(FE_DBTN4_RST_n));
   INV_X1 FE_DBTC3_delayRegOut_0 (.A(delayRegOut[0]),
	.ZN(FE_DBTN3_delayRegOut_0));
   INV_X1 FE_DBTC2_delayRegOut_3 (.A(delayRegOut[3]),
	.ZN(FE_DBTN2_delayRegOut_3));
   INV_X1 FE_DBTC1_delayRegOut_5 (.A(delayRegOut[5]),
	.ZN(FE_DBTN1_delayRegOut_5));
   INV_X1 FE_DBTC0_delayRegOut_7 (.A(delayRegOut[7]),
	.ZN(FE_DBTN0_delayRegOut_7));
   DFF_X1 current_state_reg_1_ (.D(n17),
	.CK(CLK),
	.Q(current_state[1]),
	.QN(n8));
   DFF_X1 current_state_reg_2_ (.D(N14),
	.CK(CLK),
	.Q(current_state[2]),
	.QN(n7));
   DFF_X1 current_state_reg_0_ (.D(N12),
	.CK(CLK),
	.Q(current_state[0]),
	.QN(n9));
   NAND3_X1 U14 (.A1(n15),
	.A2(n8),
	.A3(RST_n),
	.ZN(n14));
   NAND3_X1 U15 (.A1(RST_n),
	.A2(n7),
	.A3(VIN),
	.ZN(n13));
   INV_X1 U16 (.A(n11),
	.ZN(n18));
   INV_X1 U17 (.A(n13),
	.ZN(n17));
   AOI22_X1 U18 (.A1(n12),
	.A2(n11),
	.B1(current_state[1]),
	.B2(n9),
	.ZN(VOUT));
   NAND2_X1 U19 (.A1(current_state[2]),
	.A2(n9),
	.ZN(n12));
   NOR3_X1 U20 (.A1(FE_DBTN4_RST_n),
	.A2(VIN),
	.A3(n11),
	.ZN(N14));
   NAND2_X1 U22 (.A1(current_state[1]),
	.A2(n7),
	.ZN(n11));
   OAI21_X1 U23 (.A(n14),
	.B1(n8),
	.B2(n13),
	.ZN(N12));
   OAI22_X1 U24 (.A1(current_state[0]),
	.A2(n7),
	.B1(current_state[2]),
	.B2(VIN),
	.ZN(n15));
   DFFR_X1 DinReg_Q_reg_0_ (.D(DIN[1]),
	.RN(RST_n),
	.CK(CLK),
	.Q(DinRegOut[0]));
   DFFR_X1 DinReg_Q_reg_1_ (.D(DIN[2]),
	.RN(RST_n),
	.CK(CLK),
	.Q(DinRegOut[1]));
   DFFR_X1 DinReg_Q_reg_2_ (.D(DIN[3]),
	.RN(RST_n),
	.CK(CLK),
	.Q(DinRegOut[2]));
   DFFR_X1 DinReg_Q_reg_3_ (.D(DIN[4]),
	.RN(RST_n),
	.CK(CLK),
	.Q(DinRegOut[3]));
   DFFR_X1 DinReg_Q_reg_4_ (.D(DIN[5]),
	.RN(RST_n),
	.CK(CLK),
	.Q(DinRegOut[4]));
   DFFR_X1 DinReg_Q_reg_5_ (.D(DIN[6]),
	.RN(RST_n),
	.CK(CLK),
	.Q(DinRegOut[5]));
   DFFR_X1 DinReg_Q_reg_6_ (.D(DIN[7]),
	.RN(RST_n),
	.CK(CLK),
	.Q(DinRegOut[6]));
   DFFR_X1 DinReg_Q_reg_7_ (.D(DIN[8]),
	.RN(RST_n),
	.CK(CLK),
	.Q(DinRegOut[7]));
   AOI22_X1 delayReg_U19 (.A1(w_sat[6]),
	.A2(delayReg_n11),
	.B1(delayRegOut[6]),
	.B2(delayReg_n12),
	.ZN(delayReg_n18));
   INV_X1 delayReg_U18 (.A(delayReg_n18),
	.ZN(delayReg_n8));
   AOI22_X1 delayReg_U17 (.A1(w_sat[4]),
	.A2(delayReg_n11),
	.B1(delayRegOut[4]),
	.B2(delayReg_n12),
	.ZN(delayReg_n16));
   INV_X1 delayReg_U16 (.A(delayReg_n16),
	.ZN(delayReg_n6));
   AOI22_X1 delayReg_U15 (.A1(w_sat[7]),
	.A2(delayReg_n11),
	.B1(delayRegOut[7]),
	.B2(delayReg_n12),
	.ZN(delayReg_n19));
   INV_X1 delayReg_U14 (.A(delayReg_n19),
	.ZN(delayReg_n1));
   AOI22_X1 delayReg_U13 (.A1(w_sat[5]),
	.A2(delayReg_n11),
	.B1(delayRegOut[5]),
	.B2(delayReg_n12),
	.ZN(delayReg_n17));
   INV_X1 delayReg_U12 (.A(delayReg_n17),
	.ZN(delayReg_n7));
   AOI22_X1 delayReg_U11 (.A1(w_sat[3]),
	.A2(delayReg_n11),
	.B1(delayRegOut[3]),
	.B2(delayReg_n12),
	.ZN(delayReg_n15));
   INV_X1 delayReg_U10 (.A(delayReg_n15),
	.ZN(delayReg_n5));
   AOI22_X1 delayReg_U9 (.A1(w_sat[1]),
	.A2(delayReg_n11),
	.B1(FE_OFN1_delayRegOut_1),
	.B2(delayReg_n12),
	.ZN(delayReg_n13));
   INV_X1 delayReg_U8 (.A(delayReg_n13),
	.ZN(delayReg_n3));
   AOI22_X1 delayReg_U7 (.A1(w_sat[2]),
	.A2(delayReg_n11),
	.B1(delayRegOut[2]),
	.B2(delayReg_n12),
	.ZN(delayReg_n14));
   INV_X1 delayReg_U6 (.A(delayReg_n14),
	.ZN(delayReg_n4));
   AOI22_X1 delayReg_U5 (.A1(w_sat[0]),
	.A2(delayReg_n11),
	.B1(delayRegOut[0]),
	.B2(delayReg_n12),
	.ZN(delayReg_n10));
   INV_X1 delayReg_U4 (.A(delayReg_n10),
	.ZN(delayReg_n2));
   NOR2_X1 delayReg_U3 (.A1(n18),
	.A2(FE_DBTN4_RST_n),
	.ZN(delayReg_n12));
   NOR2_X1 delayReg_U2 (.A1(FE_DBTN4_RST_n),
	.A2(delayReg_n12),
	.ZN(delayReg_n11));
   DFF_X1 delayReg_feedback_reg_0_ (.D(delayReg_n2),
	.CK(CLK),
	.Q(delayRegOut[0]));
   DFF_X1 delayReg_feedback_reg_1_ (.D(delayReg_n3),
	.CK(CLK),
	.Q(delayRegOut[1]));
   DFF_X1 delayReg_feedback_reg_2_ (.D(delayReg_n4),
	.CK(CLK),
	.Q(delayRegOut[2]));
   DFF_X1 delayReg_feedback_reg_3_ (.D(delayReg_n5),
	.CK(CLK),
	.Q(delayRegOut[3]));
   DFF_X1 delayReg_feedback_reg_4_ (.D(delayReg_n6),
	.CK(CLK),
	.Q(delayRegOut[4]));
   DFF_X1 delayReg_feedback_reg_5_ (.D(delayReg_n7),
	.CK(CLK),
	.Q(delayRegOut[5]));
   DFF_X1 delayReg_feedback_reg_6_ (.D(delayReg_n8),
	.CK(CLK),
	.Q(delayRegOut[6]));
   DFF_X1 delayReg_feedback_reg_7_ (.D(delayReg_n1),
	.CK(CLK),
	.Q(delayRegOut[7]));
   AOI22_X1 DoutReg_U19 (.A1(DOUT_s_sat[7]),
	.A2(DoutReg_n28),
	.B1(DOUT[8]),
	.B2(DoutReg_n27),
	.ZN(DoutReg_n20));
   INV_X1 DoutReg_U18 (.A(DoutReg_n20),
	.ZN(DoutReg_n1));
   AOI22_X1 DoutReg_U17 (.A1(DOUT_s_sat[6]),
	.A2(DoutReg_n28),
	.B1(DOUT[7]),
	.B2(DoutReg_n27),
	.ZN(DoutReg_n21));
   INV_X1 DoutReg_U16 (.A(DoutReg_n21),
	.ZN(DoutReg_n8));
   AOI22_X1 DoutReg_U15 (.A1(DOUT_s_sat[5]),
	.A2(DoutReg_n28),
	.B1(DOUT[6]),
	.B2(DoutReg_n27),
	.ZN(DoutReg_n22));
   INV_X1 DoutReg_U14 (.A(DoutReg_n22),
	.ZN(DoutReg_n7));
   AOI22_X1 DoutReg_U13 (.A1(DOUT_s_sat[4]),
	.A2(DoutReg_n28),
	.B1(DOUT[5]),
	.B2(DoutReg_n27),
	.ZN(DoutReg_n23));
   INV_X1 DoutReg_U12 (.A(DoutReg_n23),
	.ZN(DoutReg_n6));
   AOI22_X1 DoutReg_U11 (.A1(DOUT_s_sat[3]),
	.A2(DoutReg_n28),
	.B1(DOUT[4]),
	.B2(DoutReg_n27),
	.ZN(DoutReg_n24));
   INV_X1 DoutReg_U10 (.A(DoutReg_n24),
	.ZN(DoutReg_n5));
   AOI22_X1 DoutReg_U9 (.A1(DOUT_s_sat[2]),
	.A2(DoutReg_n28),
	.B1(DOUT[3]),
	.B2(DoutReg_n27),
	.ZN(DoutReg_n25));
   INV_X1 DoutReg_U8 (.A(DoutReg_n25),
	.ZN(DoutReg_n4));
   AOI22_X1 DoutReg_U7 (.A1(DOUT_s_sat[1]),
	.A2(DoutReg_n28),
	.B1(DOUT[2]),
	.B2(DoutReg_n27),
	.ZN(DoutReg_n26));
   INV_X1 DoutReg_U6 (.A(DoutReg_n26),
	.ZN(DoutReg_n3));
   AOI22_X1 DoutReg_U5 (.A1(DOUT_s_sat[0]),
	.A2(DoutReg_n28),
	.B1(DOUT[1]),
	.B2(DoutReg_n27),
	.ZN(DoutReg_n29));
   INV_X1 DoutReg_U4 (.A(DoutReg_n29),
	.ZN(DoutReg_n2));
   NOR2_X1 DoutReg_U3 (.A1(n18),
	.A2(FE_DBTN4_RST_n),
	.ZN(DoutReg_n27));
   NOR2_X1 DoutReg_U2 (.A1(FE_DBTN4_RST_n),
	.A2(DoutReg_n27),
	.ZN(DoutReg_n28));
   DFF_X1 DoutReg_feedback_reg_0_ (.D(DoutReg_n2),
	.CK(CLK),
	.Q(DOUT[1]));
   DFF_X1 DoutReg_feedback_reg_1_ (.D(DoutReg_n3),
	.CK(CLK),
	.Q(DOUT[2]));
   DFF_X1 DoutReg_feedback_reg_2_ (.D(DoutReg_n4),
	.CK(CLK),
	.Q(DOUT[3]));
   DFF_X1 DoutReg_feedback_reg_3_ (.D(DoutReg_n5),
	.CK(CLK),
	.Q(DOUT[4]));
   DFF_X1 DoutReg_feedback_reg_4_ (.D(DoutReg_n6),
	.CK(CLK),
	.Q(DOUT[5]));
   DFF_X1 DoutReg_feedback_reg_5_ (.D(DoutReg_n7),
	.CK(CLK),
	.Q(DOUT[6]));
   DFF_X1 DoutReg_feedback_reg_6_ (.D(DoutReg_n8),
	.CK(CLK),
	.Q(DOUT[7]));
   DFF_X1 DoutReg_feedback_reg_7_ (.D(DoutReg_n1),
	.CK(CLK),
	.Q(DOUT[8]));
   AND2_X1 chk_ovf_fb_U13 (.A1(H3[8]),
	.A2(delayRegOut[7]),
	.ZN(chk_ovf_fb_n2));
   OR2_X1 chk_ovf_fb_U12 (.A1(feedback[13]),
	.A2(chk_ovf_fb_n3),
	.ZN(feedback_sat[6]));
   OR2_X1 chk_ovf_fb_U11 (.A1(feedback[12]),
	.A2(chk_ovf_fb_n3),
	.ZN(feedback_sat[5]));
   OR2_X1 chk_ovf_fb_U10 (.A1(feedback[11]),
	.A2(chk_ovf_fb_n3),
	.ZN(feedback_sat[4]));
   OR2_X1 chk_ovf_fb_U9 (.A1(feedback[10]),
	.A2(chk_ovf_fb_n3),
	.ZN(feedback_sat[3]));
   OR2_X1 chk_ovf_fb_U8 (.A1(feedback[9]),
	.A2(chk_ovf_fb_n3),
	.ZN(feedback_sat[2]));
   OR2_X1 chk_ovf_fb_U7 (.A1(feedback[8]),
	.A2(chk_ovf_fb_n3),
	.ZN(feedback_sat[1]));
   INV_X1 chk_ovf_fb_U6 (.A(feedback[14]),
	.ZN(chk_ovf_fb_n1));
   NOR2_X1 chk_ovf_fb_U5 (.A1(chk_ovf_fb_n2),
	.A2(chk_ovf_fb_n1),
	.ZN(feedback_sat[7]));
   AND2_X1 chk_ovf_fb_U4 (.A1(chk_ovf_fb_n2),
	.A2(feedback[14]),
	.ZN(chk_ovf_fb_n3));
   OR2_X1 chk_ovf_fb_U3 (.A1(feedback[7]),
	.A2(chk_ovf_fb_n3),
	.ZN(feedback_sat[0]));
   AND2_X1 chk_ovf_ff_U13 (.A1(H1[8]),
	.A2(delayRegOut[7]),
	.ZN(chk_ovf_ff_n5));
   AND2_X1 chk_ovf_ff_U12 (.A1(chk_ovf_ff_n5),
	.A2(feedforward[14]),
	.ZN(chk_ovf_ff_n4));
   INV_X1 chk_ovf_ff_U11 (.A(feedforward[14]),
	.ZN(chk_ovf_ff_n1));
   NOR2_X1 chk_ovf_ff_U10 (.A1(chk_ovf_ff_n5),
	.A2(chk_ovf_ff_n1),
	.ZN(feedforward_sat[7]));
   OR2_X1 chk_ovf_ff_U9 (.A1(feedforward[7]),
	.A2(chk_ovf_ff_n4),
	.ZN(feedforward_sat[0]));
   OR2_X1 chk_ovf_ff_U8 (.A1(feedforward[13]),
	.A2(chk_ovf_ff_n4),
	.ZN(feedforward_sat[6]));
   OR2_X1 chk_ovf_ff_U7 (.A1(feedforward[12]),
	.A2(chk_ovf_ff_n4),
	.ZN(feedforward_sat[5]));
   OR2_X1 chk_ovf_ff_U6 (.A1(feedforward[11]),
	.A2(chk_ovf_ff_n4),
	.ZN(feedforward_sat[4]));
   OR2_X1 chk_ovf_ff_U5 (.A1(feedforward[10]),
	.A2(chk_ovf_ff_n4),
	.ZN(feedforward_sat[3]));
   OR2_X1 chk_ovf_ff_U4 (.A1(feedforward[9]),
	.A2(chk_ovf_ff_n4),
	.ZN(feedforward_sat[2]));
   OR2_X1 chk_ovf_ff_U3 (.A1(feedforward[8]),
	.A2(chk_ovf_ff_n4),
	.ZN(feedforward_sat[1]));
   INV_X1 chk_ovf_w_U21 (.A(DinRegOut[7]),
	.ZN(chk_ovf_w_n2));
   NAND2_X1 chk_ovf_w_U20 (.A1(w[0]),
	.A2(chk_ovf_w_n6),
	.ZN(chk_ovf_w_n12));
   NAND2_X1 chk_ovf_w_U19 (.A1(chk_ovf_w_n4),
	.A2(chk_ovf_w_n12),
	.ZN(w_sat[0]));
   INV_X1 chk_ovf_w_U18 (.A(w[7]),
	.ZN(chk_ovf_w_n1));
   NOR2_X1 chk_ovf_w_U17 (.A1(w[7]),
	.A2(DinRegOut[7]),
	.ZN(chk_ovf_w_n3));
   OAI22_X1 chk_ovf_w_U16 (.A1(feedback_sat[7]),
	.A2(chk_ovf_w_n3),
	.B1(chk_ovf_w_n2),
	.B2(chk_ovf_w_n1),
	.ZN(w_sat[7]));
   OR3_X1 chk_ovf_w_U15 (.A1(feedback_sat[7]),
	.A2(w[7]),
	.A3(chk_ovf_w_n2),
	.ZN(chk_ovf_w_n6));
   NAND2_X1 chk_ovf_w_U14 (.A1(w[2]),
	.A2(chk_ovf_w_n6),
	.ZN(chk_ovf_w_n10));
   NAND2_X1 chk_ovf_w_U13 (.A1(chk_ovf_w_n4),
	.A2(chk_ovf_w_n10),
	.ZN(w_sat[2]));
   NAND2_X1 chk_ovf_w_U12 (.A1(w[6]),
	.A2(chk_ovf_w_n6),
	.ZN(chk_ovf_w_n5));
   NAND2_X1 chk_ovf_w_U11 (.A1(chk_ovf_w_n4),
	.A2(chk_ovf_w_n5),
	.ZN(w_sat[6]));
   NAND2_X1 chk_ovf_w_U10 (.A1(w[4]),
	.A2(chk_ovf_w_n6),
	.ZN(chk_ovf_w_n8));
   NAND2_X1 chk_ovf_w_U9 (.A1(chk_ovf_w_n4),
	.A2(chk_ovf_w_n8),
	.ZN(w_sat[4]));
   NAND2_X1 chk_ovf_w_U8 (.A1(w[5]),
	.A2(chk_ovf_w_n6),
	.ZN(chk_ovf_w_n7));
   NAND2_X1 chk_ovf_w_U7 (.A1(chk_ovf_w_n4),
	.A2(chk_ovf_w_n7),
	.ZN(w_sat[5]));
   NAND2_X1 chk_ovf_w_U6 (.A1(w[1]),
	.A2(chk_ovf_w_n6),
	.ZN(chk_ovf_w_n11));
   NAND2_X1 chk_ovf_w_U5 (.A1(chk_ovf_w_n4),
	.A2(chk_ovf_w_n11),
	.ZN(w_sat[1]));
   NAND2_X1 chk_ovf_w_U4 (.A1(w[3]),
	.A2(chk_ovf_w_n6),
	.ZN(chk_ovf_w_n9));
   NAND2_X1 chk_ovf_w_U3 (.A1(chk_ovf_w_n4),
	.A2(chk_ovf_w_n9),
	.ZN(w_sat[3]));
   NAND3_X1 chk_ovf_w_U22 (.A1(w[7]),
	.A2(chk_ovf_w_n2),
	.A3(feedback_sat[7]),
	.ZN(chk_ovf_w_n4));
   AND2_X1 chk_ovf_multb0_U13 (.A1(H0[8]),
	.A2(w[7]),
	.ZN(chk_ovf_multb0_n5));
   INV_X1 chk_ovf_multb0_U12 (.A(multb0[14]),
	.ZN(chk_ovf_multb0_n1));
   NOR2_X1 chk_ovf_multb0_U11 (.A1(chk_ovf_multb0_n5),
	.A2(chk_ovf_multb0_n1),
	.ZN(multb0_sat[7]));
   AND2_X1 chk_ovf_multb0_U10 (.A1(chk_ovf_multb0_n5),
	.A2(multb0[14]),
	.ZN(chk_ovf_multb0_n4));
   OR2_X1 chk_ovf_multb0_U9 (.A1(multb0[7]),
	.A2(chk_ovf_multb0_n4),
	.ZN(multb0_sat[0]));
   OR2_X1 chk_ovf_multb0_U8 (.A1(multb0[13]),
	.A2(chk_ovf_multb0_n4),
	.ZN(multb0_sat[6]));
   OR2_X1 chk_ovf_multb0_U7 (.A1(multb0[12]),
	.A2(chk_ovf_multb0_n4),
	.ZN(multb0_sat[5]));
   OR2_X1 chk_ovf_multb0_U6 (.A1(multb0[11]),
	.A2(chk_ovf_multb0_n4),
	.ZN(multb0_sat[4]));
   OR2_X1 chk_ovf_multb0_U5 (.A1(multb0[10]),
	.A2(chk_ovf_multb0_n4),
	.ZN(multb0_sat[3]));
   OR2_X1 chk_ovf_multb0_U4 (.A1(multb0[9]),
	.A2(chk_ovf_multb0_n4),
	.ZN(multb0_sat[2]));
   OR2_X1 chk_ovf_multb0_U3 (.A1(multb0[8]),
	.A2(chk_ovf_multb0_n4),
	.ZN(multb0_sat[1]));
   NOR2_X1 chk_ovf_douts_U22 (.A1(multb0_sat[7]),
	.A2(feedforward_sat[7]),
	.ZN(chk_ovf_douts_n9));
   OAI21_X1 chk_ovf_douts_U21 (.A(chk_ovf_douts_n10),
	.B1(chk_ovf_douts_n9),
	.B2(chk_ovf_douts_n1),
	.ZN(DOUT_s_sat[7]));
   INV_X1 chk_ovf_douts_U20 (.A(DOUT_s[6]),
	.ZN(chk_ovf_douts_n2));
   OAI21_X1 chk_ovf_douts_U19 (.A(chk_ovf_douts_n12),
	.B1(chk_ovf_douts_n11),
	.B2(chk_ovf_douts_n2),
	.ZN(DOUT_s_sat[6]));
   INV_X1 chk_ovf_douts_U18 (.A(DOUT_s[5]),
	.ZN(chk_ovf_douts_n3));
   OAI21_X1 chk_ovf_douts_U17 (.A(chk_ovf_douts_n12),
	.B1(chk_ovf_douts_n11),
	.B2(chk_ovf_douts_n3),
	.ZN(DOUT_s_sat[5]));
   INV_X1 chk_ovf_douts_U16 (.A(DOUT_s[4]),
	.ZN(chk_ovf_douts_n4));
   OAI21_X1 chk_ovf_douts_U15 (.A(chk_ovf_douts_n12),
	.B1(chk_ovf_douts_n11),
	.B2(chk_ovf_douts_n4),
	.ZN(DOUT_s_sat[4]));
   INV_X1 chk_ovf_douts_U14 (.A(DOUT_s[3]),
	.ZN(chk_ovf_douts_n5));
   OAI21_X1 chk_ovf_douts_U13 (.A(chk_ovf_douts_n12),
	.B1(chk_ovf_douts_n11),
	.B2(chk_ovf_douts_n5),
	.ZN(DOUT_s_sat[3]));
   INV_X1 chk_ovf_douts_U12 (.A(DOUT_s[2]),
	.ZN(chk_ovf_douts_n6));
   OAI21_X1 chk_ovf_douts_U11 (.A(chk_ovf_douts_n12),
	.B1(chk_ovf_douts_n11),
	.B2(chk_ovf_douts_n6),
	.ZN(DOUT_s_sat[2]));
   INV_X1 chk_ovf_douts_U10 (.A(DOUT_s[1]),
	.ZN(chk_ovf_douts_n7));
   OAI21_X1 chk_ovf_douts_U9 (.A(chk_ovf_douts_n12),
	.B1(chk_ovf_douts_n11),
	.B2(chk_ovf_douts_n7),
	.ZN(DOUT_s_sat[1]));
   INV_X1 chk_ovf_douts_U8 (.A(DOUT_s[0]),
	.ZN(chk_ovf_douts_n8));
   OAI21_X1 chk_ovf_douts_U7 (.A(chk_ovf_douts_n12),
	.B1(chk_ovf_douts_n11),
	.B2(chk_ovf_douts_n8),
	.ZN(DOUT_s_sat[0]));
   NAND2_X1 chk_ovf_douts_U6 (.A1(feedforward_sat[7]),
	.A2(multb0_sat[7]),
	.ZN(chk_ovf_douts_n10));
   OR3_X1 chk_ovf_douts_U5 (.A1(multb0_sat[7]),
	.A2(feedforward_sat[7]),
	.A3(chk_ovf_douts_n1),
	.ZN(chk_ovf_douts_n12));
   INV_X1 chk_ovf_douts_U4 (.A(DOUT_s[7]),
	.ZN(chk_ovf_douts_n1));
   NOR2_X1 chk_ovf_douts_U3 (.A1(chk_ovf_douts_n10),
	.A2(DOUT_s[7]),
	.ZN(chk_ovf_douts_n11));
   XOR2_X1 add_177_U2 (.A(feedforward_sat[0]),
	.B(multb0_sat[0]),
	.Z(DOUT_s[0]));
   AND2_X1 add_177_U1 (.A1(feedforward_sat[0]),
	.A2(multb0_sat[0]),
	.ZN(add_177_n1));
   FA_X1 add_177_U1_1 (.A(multb0_sat[1]),
	.B(feedforward_sat[1]),
	.CI(add_177_n1),
	.CO(add_177_carry[2]),
	.S(DOUT_s[1]));
   FA_X1 add_177_U1_2 (.A(multb0_sat[2]),
	.B(feedforward_sat[2]),
	.CI(add_177_carry[2]),
	.CO(add_177_carry[3]),
	.S(DOUT_s[2]));
   FA_X1 add_177_U1_3 (.A(multb0_sat[3]),
	.B(feedforward_sat[3]),
	.CI(add_177_carry[3]),
	.CO(add_177_carry[4]),
	.S(DOUT_s[3]));
   FA_X1 add_177_U1_4 (.A(multb0_sat[4]),
	.B(feedforward_sat[4]),
	.CI(add_177_carry[4]),
	.CO(add_177_carry[5]),
	.S(DOUT_s[4]));
   FA_X1 add_177_U1_5 (.A(multb0_sat[5]),
	.B(feedforward_sat[5]),
	.CI(add_177_carry[5]),
	.CO(add_177_carry[6]),
	.S(DOUT_s[5]));
   FA_X1 add_177_U1_6 (.A(multb0_sat[6]),
	.B(feedforward_sat[6]),
	.CI(add_177_carry[6]),
	.CO(add_177_carry[7]),
	.S(DOUT_s[6]));
   FA_X1 add_177_U1_7 (.A(multb0_sat[7]),
	.B(feedforward_sat[7]),
	.CI(add_177_carry[7]),
	.S(DOUT_s[7]));
   INV_X1 sub_169_U11 (.A(DinRegOut[0]),
	.ZN(sub_169_n1));
   INV_X1 sub_169_U10 (.A(feedback_sat[6]),
	.ZN(sub_169_n9));
   INV_X1 sub_169_U9 (.A(feedback_sat[5]),
	.ZN(sub_169_n8));
   INV_X1 sub_169_U8 (.A(feedback_sat[4]),
	.ZN(sub_169_n7));
   INV_X1 sub_169_U7 (.A(feedback_sat[3]),
	.ZN(sub_169_n6));
   INV_X1 sub_169_U6 (.A(feedback_sat[2]),
	.ZN(sub_169_n5));
   NAND2_X1 sub_169_U5 (.A1(feedback_sat[0]),
	.A2(sub_169_n1),
	.ZN(sub_169_carry[1]));
   INV_X1 sub_169_U4 (.A(feedback_sat[1]),
	.ZN(sub_169_n4));
   XNOR2_X1 sub_169_U3 (.A(sub_169_n3),
	.B(DinRegOut[0]),
	.ZN(w[0]));
   INV_X1 sub_169_U2 (.A(feedback_sat[7]),
	.ZN(sub_169_n2));
   INV_X1 sub_169_U1 (.A(feedback_sat[0]),
	.ZN(sub_169_n3));
   FA_X1 sub_169_U2_1 (.A(DinRegOut[1]),
	.B(sub_169_n4),
	.CI(sub_169_carry[1]),
	.CO(sub_169_carry[2]),
	.S(w[1]));
   FA_X1 sub_169_U2_2 (.A(DinRegOut[2]),
	.B(sub_169_n5),
	.CI(sub_169_carry[2]),
	.CO(sub_169_carry[3]),
	.S(w[2]));
   FA_X1 sub_169_U2_3 (.A(DinRegOut[3]),
	.B(sub_169_n6),
	.CI(sub_169_carry[3]),
	.CO(sub_169_carry[4]),
	.S(w[3]));
   FA_X1 sub_169_U2_4 (.A(DinRegOut[4]),
	.B(sub_169_n7),
	.CI(sub_169_carry[4]),
	.CO(sub_169_carry[5]),
	.S(w[4]));
   FA_X1 sub_169_U2_5 (.A(DinRegOut[5]),
	.B(sub_169_n8),
	.CI(sub_169_carry[5]),
	.CO(sub_169_carry[6]),
	.S(w[5]));
   FA_X1 sub_169_U2_6 (.A(DinRegOut[6]),
	.B(sub_169_n9),
	.CI(sub_169_carry[6]),
	.CO(sub_169_carry[7]),
	.S(w[6]));
   FA_X1 sub_169_U2_7 (.A(DinRegOut[7]),
	.B(sub_169_n2),
	.CI(sub_169_carry[7]),
	.S(w[7]));
   XNOR2_X1 mult_162_U266 (.A(H1[5]),
	.B(FE_OFN1_delayRegOut_1),
	.ZN(mult_162_n282));
   NAND2_X1 mult_162_U265 (.A1(FE_OFN1_delayRegOut_1),
	.A2(FE_DBTN3_delayRegOut_0),
	.ZN(mult_162_n228));
   XNOR2_X1 mult_162_U264 (.A(H1[6]),
	.B(FE_OFN1_delayRegOut_1),
	.ZN(mult_162_n227));
   OAI22_X1 mult_162_U263 (.A1(mult_162_n282),
	.A2(mult_162_n228),
	.B1(mult_162_n227),
	.B2(FE_DBTN3_delayRegOut_0),
	.ZN(mult_162_n100));
   XNOR2_X1 mult_162_U262 (.A(H1[4]),
	.B(FE_OFN1_delayRegOut_1),
	.ZN(mult_162_n281));
   OAI22_X1 mult_162_U261 (.A1(mult_162_n281),
	.A2(mult_162_n228),
	.B1(mult_162_n282),
	.B2(FE_DBTN3_delayRegOut_0),
	.ZN(mult_162_n101));
   XNOR2_X1 mult_162_U260 (.A(H1[3]),
	.B(FE_OFN1_delayRegOut_1),
	.ZN(mult_162_n249));
   OAI22_X1 mult_162_U259 (.A1(mult_162_n249),
	.A2(mult_162_n228),
	.B1(mult_162_n281),
	.B2(FE_DBTN3_delayRegOut_0),
	.ZN(mult_162_n102));
   XOR2_X1 mult_162_U258 (.A(H1[7]),
	.B(FE_DBTN0_delayRegOut_7),
	.Z(mult_162_n270));
   XOR2_X1 mult_162_U257 (.A(delayRegOut[7]),
	.B(delayRegOut[6]),
	.Z(mult_162_n280));
   NAND2_X1 mult_162_U256 (.A1(mult_162_n262),
	.A2(mult_162_n280),
	.ZN(mult_162_n264));
   XOR2_X1 mult_162_U255 (.A(H1[8]),
	.B(FE_DBTN0_delayRegOut_7),
	.Z(mult_162_n272));
   OAI22_X1 mult_162_U254 (.A1(mult_162_n270),
	.A2(mult_162_n264),
	.B1(mult_162_n262),
	.B2(mult_162_n272),
	.ZN(mult_162_n15));
   XOR2_X1 mult_162_U253 (.A(H1[7]),
	.B(FE_DBTN1_delayRegOut_5),
	.Z(mult_162_n259));
   XNOR2_X1 mult_162_U252 (.A(delayRegOut[4]),
	.B(delayRegOut[3]),
	.ZN(mult_162_n251));
   XOR2_X1 mult_162_U251 (.A(delayRegOut[5]),
	.B(delayRegOut[4]),
	.Z(mult_162_n279));
   NAND2_X1 mult_162_U250 (.A1(mult_162_n251),
	.A2(mult_162_n279),
	.ZN(mult_162_n253));
   XOR2_X1 mult_162_U249 (.A(H1[8]),
	.B(FE_DBTN1_delayRegOut_5),
	.Z(mult_162_n261));
   OAI22_X1 mult_162_U248 (.A1(mult_162_n259),
	.A2(mult_162_n253),
	.B1(mult_162_n251),
	.B2(mult_162_n261),
	.ZN(mult_162_n21));
   XOR2_X1 mult_162_U247 (.A(H1[7]),
	.B(delayRegOut[3]),
	.Z(mult_162_n277));
   XNOR2_X1 mult_162_U246 (.A(delayRegOut[2]),
	.B(FE_OFN1_delayRegOut_1),
	.ZN(mult_162_n234));
   XOR2_X1 mult_162_U245 (.A(delayRegOut[3]),
	.B(delayRegOut[2]),
	.Z(mult_162_n278));
   NAND2_X1 mult_162_U244 (.A1(mult_162_n234),
	.A2(mult_162_n278),
	.ZN(mult_162_n233));
   XOR2_X1 mult_162_U243 (.A(H1[8]),
	.B(delayRegOut[3]),
	.Z(mult_162_n250));
   AOI22_X1 mult_162_U242 (.A1(mult_162_n277),
	.A2(mult_162_n221),
	.B1(mult_162_n222),
	.B2(mult_162_n250),
	.ZN(mult_162_n32));
   XOR2_X1 mult_162_U241 (.A(mult_162_n225),
	.B(delayRegOut[7]),
	.Z(mult_162_n265));
   XOR2_X1 mult_162_U240 (.A(H1[3]),
	.B(FE_DBTN0_delayRegOut_7),
	.Z(mult_162_n266));
   OAI22_X1 mult_162_U239 (.A1(mult_162_n265),
	.A2(mult_162_n264),
	.B1(mult_162_n262),
	.B2(mult_162_n266),
	.ZN(mult_162_n275));
   XOR2_X1 mult_162_U238 (.A(H1[6]),
	.B(FE_DBTN2_delayRegOut_3),
	.Z(mult_162_n239));
   AOI22_X1 mult_162_U237 (.A1(mult_162_n218),
	.A2(mult_162_n221),
	.B1(mult_162_n222),
	.B2(mult_162_n277),
	.ZN(mult_162_n276));
   NAND2_X1 mult_162_U236 (.A1(mult_162_n207),
	.A2(mult_162_n276),
	.ZN(mult_162_n37));
   XOR2_X1 mult_162_U235 (.A(mult_162_n275),
	.B(mult_162_n276),
	.Z(mult_162_n38));
   OR3_X1 mult_162_U234 (.A1(mult_162_n262),
	.A2(H1[1]),
	.A3(FE_DBTN0_delayRegOut_7),
	.ZN(mult_162_n274));
   OAI21_X1 mult_162_U233 (.A(mult_162_n274),
	.B1(FE_DBTN0_delayRegOut_7),
	.B2(mult_162_n264),
	.ZN(mult_162_n69));
   OR3_X1 mult_162_U232 (.A1(mult_162_n251),
	.A2(H1[1]),
	.A3(FE_DBTN1_delayRegOut_5),
	.ZN(mult_162_n273));
   OAI21_X1 mult_162_U231 (.A(mult_162_n273),
	.B1(FE_DBTN1_delayRegOut_5),
	.B2(mult_162_n253),
	.ZN(mult_162_n70));
   XOR2_X1 mult_162_U229 (.A(H1[6]),
	.B(FE_DBTN0_delayRegOut_7),
	.Z(mult_162_n269));
   OAI22_X1 mult_162_U228 (.A1(mult_162_n269),
	.A2(mult_162_n264),
	.B1(mult_162_n262),
	.B2(mult_162_n270),
	.ZN(mult_162_n74));
   XOR2_X1 mult_162_U227 (.A(H1[5]),
	.B(FE_DBTN0_delayRegOut_7),
	.Z(mult_162_n268));
   OAI22_X1 mult_162_U226 (.A1(mult_162_n268),
	.A2(mult_162_n264),
	.B1(mult_162_n262),
	.B2(mult_162_n269),
	.ZN(mult_162_n75));
   XOR2_X1 mult_162_U225 (.A(H1[4]),
	.B(FE_DBTN0_delayRegOut_7),
	.Z(mult_162_n267));
   OAI22_X1 mult_162_U224 (.A1(mult_162_n267),
	.A2(mult_162_n264),
	.B1(mult_162_n262),
	.B2(mult_162_n268),
	.ZN(mult_162_n76));
   OAI22_X1 mult_162_U223 (.A1(mult_162_n266),
	.A2(mult_162_n264),
	.B1(mult_162_n262),
	.B2(mult_162_n267),
	.ZN(mult_162_n77));
   XOR2_X1 mult_162_U222 (.A(FE_DBTN0_delayRegOut_7),
	.B(H1[1]),
	.Z(mult_162_n263));
   OAI22_X1 mult_162_U221 (.A1(mult_162_n263),
	.A2(mult_162_n264),
	.B1(mult_162_n262),
	.B2(mult_162_n265),
	.ZN(mult_162_n79));
   NOR2_X1 mult_162_U220 (.A1(mult_162_n262),
	.A2(mult_162_n226),
	.ZN(mult_162_n80));
   OAI22_X1 mult_162_U219 (.A1(mult_162_n261),
	.A2(mult_162_n251),
	.B1(mult_162_n253),
	.B2(mult_162_n261),
	.ZN(mult_162_n260));
   XOR2_X1 mult_162_U218 (.A(H1[6]),
	.B(FE_DBTN1_delayRegOut_5),
	.Z(mult_162_n258));
   OAI22_X1 mult_162_U217 (.A1(mult_162_n258),
	.A2(mult_162_n253),
	.B1(mult_162_n251),
	.B2(mult_162_n259),
	.ZN(mult_162_n82));
   XOR2_X1 mult_162_U216 (.A(H1[5]),
	.B(FE_DBTN1_delayRegOut_5),
	.Z(mult_162_n257));
   OAI22_X1 mult_162_U215 (.A1(mult_162_n257),
	.A2(mult_162_n253),
	.B1(mult_162_n251),
	.B2(mult_162_n258),
	.ZN(mult_162_n83));
   XOR2_X1 mult_162_U214 (.A(H1[4]),
	.B(FE_DBTN1_delayRegOut_5),
	.Z(mult_162_n256));
   OAI22_X1 mult_162_U213 (.A1(mult_162_n256),
	.A2(mult_162_n253),
	.B1(mult_162_n251),
	.B2(mult_162_n257),
	.ZN(mult_162_n84));
   XOR2_X1 mult_162_U212 (.A(H1[3]),
	.B(FE_DBTN1_delayRegOut_5),
	.Z(mult_162_n255));
   OAI22_X1 mult_162_U211 (.A1(mult_162_n255),
	.A2(mult_162_n253),
	.B1(mult_162_n251),
	.B2(mult_162_n256),
	.ZN(mult_162_n85));
   XOR2_X1 mult_162_U210 (.A(mult_162_n225),
	.B(delayRegOut[5]),
	.Z(mult_162_n254));
   OAI22_X1 mult_162_U209 (.A1(mult_162_n254),
	.A2(mult_162_n253),
	.B1(mult_162_n251),
	.B2(mult_162_n255),
	.ZN(mult_162_n86));
   XOR2_X1 mult_162_U208 (.A(mult_162_n226),
	.B(delayRegOut[5]),
	.Z(mult_162_n252));
   OAI22_X1 mult_162_U207 (.A1(mult_162_n252),
	.A2(mult_162_n253),
	.B1(mult_162_n251),
	.B2(mult_162_n254),
	.ZN(mult_162_n87));
   NOR2_X1 mult_162_U206 (.A1(mult_162_n251),
	.A2(mult_162_n226),
	.ZN(mult_162_n88));
   OAI22_X1 mult_162_U204 (.A1(H1[2]),
	.A2(mult_162_n228),
	.B1(mult_162_n249),
	.B2(FE_DBTN3_delayRegOut_0),
	.ZN(mult_162_n248));
   NAND3_X1 mult_162_U203 (.A1(mult_162_n248),
	.A2(mult_162_n225),
	.A3(FE_OFN1_delayRegOut_1),
	.ZN(mult_162_n246));
   NAND2_X1 mult_162_U202 (.A1(mult_162_n222),
	.A2(mult_162_n248),
	.ZN(mult_162_n247));
   MUX2_X1 mult_162_U201 (.A(mult_162_n246),
	.B(mult_162_n247),
	.S(H1[1]),
	.Z(mult_162_n243));
   NOR3_X1 mult_162_U200 (.A1(mult_162_n234),
	.A2(H1[1]),
	.A3(FE_DBTN2_delayRegOut_3),
	.ZN(mult_162_n245));
   AOI21_X1 mult_162_U199 (.A(mult_162_n245),
	.B1(delayRegOut[3]),
	.B2(mult_162_n221),
	.ZN(mult_162_n244));
   OAI222_X1 mult_162_U198 (.A1(mult_162_n243),
	.A2(mult_162_n217),
	.B1(mult_162_n244),
	.B2(mult_162_n243),
	.C1(mult_162_n244),
	.C2(mult_162_n217),
	.ZN(mult_162_n242));
   AOI222_X1 mult_162_U197 (.A1(mult_162_n242),
	.A2(mult_162_n54),
	.B1(mult_162_n242),
	.B2(mult_162_n55),
	.C1(mult_162_n55),
	.C2(mult_162_n54),
	.ZN(mult_162_n241));
   AOI222_X1 mult_162_U196 (.A1(mult_162_n216),
	.A2(mult_162_n50),
	.B1(mult_162_n216),
	.B2(mult_162_n53),
	.C1(mult_162_n53),
	.C2(mult_162_n50),
	.ZN(mult_162_n240));
   OAI222_X1 mult_162_U195 (.A1(mult_162_n240),
	.A2(mult_162_n211),
	.B1(mult_162_n240),
	.B2(mult_162_n212),
	.C1(mult_162_n212),
	.C2(mult_162_n211),
	.ZN(mult_162_n9));
   XOR2_X1 mult_162_U194 (.A(H1[5]),
	.B(FE_DBTN2_delayRegOut_3),
	.Z(mult_162_n238));
   OAI22_X1 mult_162_U193 (.A1(mult_162_n238),
	.A2(mult_162_n233),
	.B1(mult_162_n234),
	.B2(mult_162_n239),
	.ZN(mult_162_n91));
   XOR2_X1 mult_162_U192 (.A(H1[4]),
	.B(FE_DBTN2_delayRegOut_3),
	.Z(mult_162_n237));
   OAI22_X1 mult_162_U191 (.A1(mult_162_n237),
	.A2(mult_162_n233),
	.B1(mult_162_n234),
	.B2(mult_162_n238),
	.ZN(mult_162_n92));
   XOR2_X1 mult_162_U190 (.A(H1[3]),
	.B(FE_DBTN2_delayRegOut_3),
	.Z(mult_162_n236));
   OAI22_X1 mult_162_U189 (.A1(mult_162_n236),
	.A2(mult_162_n233),
	.B1(mult_162_n234),
	.B2(mult_162_n237),
	.ZN(mult_162_n93));
   XOR2_X1 mult_162_U188 (.A(mult_162_n225),
	.B(delayRegOut[3]),
	.Z(mult_162_n235));
   OAI22_X1 mult_162_U187 (.A1(mult_162_n235),
	.A2(mult_162_n233),
	.B1(mult_162_n234),
	.B2(mult_162_n236),
	.ZN(mult_162_n94));
   XOR2_X1 mult_162_U186 (.A(mult_162_n226),
	.B(delayRegOut[3]),
	.Z(mult_162_n232));
   OAI22_X1 mult_162_U185 (.A1(mult_162_n232),
	.A2(mult_162_n233),
	.B1(mult_162_n234),
	.B2(mult_162_n235),
	.ZN(mult_162_n95));
   XNOR2_X1 mult_162_U184 (.A(H1[8]),
	.B(FE_OFN1_delayRegOut_1),
	.ZN(mult_162_n230));
   OAI22_X1 mult_162_U183 (.A1(FE_DBTN3_delayRegOut_0),
	.A2(mult_162_n230),
	.B1(mult_162_n228),
	.B2(mult_162_n230),
	.ZN(mult_162_n231));
   XNOR2_X1 mult_162_U182 (.A(H1[7]),
	.B(FE_OFN1_delayRegOut_1),
	.ZN(mult_162_n229));
   OAI22_X1 mult_162_U181 (.A1(mult_162_n229),
	.A2(mult_162_n228),
	.B1(mult_162_n230),
	.B2(FE_DBTN3_delayRegOut_0),
	.ZN(mult_162_n98));
   OAI22_X1 mult_162_U180 (.A1(mult_162_n227),
	.A2(mult_162_n228),
	.B1(mult_162_n229),
	.B2(FE_DBTN3_delayRegOut_0),
	.ZN(mult_162_n99));
   NOR2_X1 mult_162_U179 (.A1(FE_DBTN3_delayRegOut_0),
	.A2(mult_162_n226),
	.ZN(feedforward[0]));
   INV_X1 mult_162_U178 (.A(mult_162_n56),
	.ZN(mult_162_n217));
   INV_X1 mult_162_U177 (.A(H1[2]),
	.ZN(mult_162_n225));
   INV_X1 mult_162_U176 (.A(H1[1]),
	.ZN(mult_162_n226));
   XNOR2_X1 mult_162_U171 (.A(delayRegOut[6]),
	.B(delayRegOut[5]),
	.ZN(mult_162_n262));
   INV_X1 mult_162_U170 (.A(mult_162_n32),
	.ZN(mult_162_n220));
   INV_X1 mult_162_U169 (.A(mult_162_n231),
	.ZN(mult_162_n223));
   INV_X1 mult_162_U168 (.A(mult_162_n260),
	.ZN(mult_162_n214));
   INV_X1 mult_162_U167 (.A(mult_162_n21),
	.ZN(mult_162_n213));
   INV_X1 mult_162_U166 (.A(mult_162_n233),
	.ZN(mult_162_n221));
   INV_X1 mult_162_U165 (.A(mult_162_n271),
	.ZN(mult_162_n209));
   INV_X1 mult_162_U164 (.A(mult_162_n234),
	.ZN(mult_162_n222));
   INV_X1 mult_162_U163 (.A(mult_162_n239),
	.ZN(mult_162_n218));
   INV_X1 mult_162_U162 (.A(mult_162_n241),
	.ZN(mult_162_n216));
   INV_X1 mult_162_U161 (.A(mult_162_n1),
	.ZN(feedforward[15]));
   INV_X1 mult_162_U160 (.A(mult_162_n15),
	.ZN(mult_162_n208));
   INV_X1 mult_162_U159 (.A(mult_162_n46),
	.ZN(mult_162_n211));
   INV_X1 mult_162_U158 (.A(mult_162_n49),
	.ZN(mult_162_n212));
   INV_X1 mult_162_U157 (.A(mult_162_n275),
	.ZN(mult_162_n207));
   HA_X1 mult_162_U37 (.A(mult_162_n95),
	.B(mult_162_n102),
	.CO(mult_162_n55),
	.S(mult_162_n56));
   FA_X1 mult_162_U36 (.A(mult_162_n101),
	.B(mult_162_n88),
	.CI(mult_162_n94),
	.CO(mult_162_n53),
	.S(mult_162_n54));
   HA_X1 mult_162_U35 (.A(mult_162_n70),
	.B(mult_162_n87),
	.CO(mult_162_n51),
	.S(mult_162_n52));
   FA_X1 mult_162_U34 (.A(mult_162_n93),
	.B(mult_162_n100),
	.CI(mult_162_n52),
	.CO(mult_162_n49),
	.S(mult_162_n50));
   FA_X1 mult_162_U33 (.A(mult_162_n99),
	.B(mult_162_n80),
	.CI(mult_162_n92),
	.CO(mult_162_n47),
	.S(mult_162_n48));
   FA_X1 mult_162_U32 (.A(mult_162_n51),
	.B(mult_162_n86),
	.CI(mult_162_n48),
	.CO(mult_162_n45),
	.S(mult_162_n46));
   HA_X1 mult_162_U31 (.A(mult_162_n69),
	.B(mult_162_n79),
	.CO(mult_162_n43),
	.S(mult_162_n44));
   FA_X1 mult_162_U30 (.A(mult_162_n85),
	.B(mult_162_n98),
	.CI(mult_162_n91),
	.CO(mult_162_n41),
	.S(mult_162_n42));
   FA_X1 mult_162_U29 (.A(mult_162_n47),
	.B(mult_162_n44),
	.CI(mult_162_n42),
	.CO(mult_162_n39),
	.S(mult_162_n40));
   FA_X1 mult_162_U26 (.A(mult_162_n223),
	.B(mult_162_n84),
	.CI(mult_162_n43),
	.CO(mult_162_n35),
	.S(mult_162_n36));
   FA_X1 mult_162_U25 (.A(mult_162_n41),
	.B(mult_162_n38),
	.CI(mult_162_n36),
	.CO(mult_162_n33),
	.S(mult_162_n34));
   FA_X1 mult_162_U23 (.A(mult_162_n77),
	.B(mult_162_n83),
	.CI(mult_162_n32),
	.CO(mult_162_n29),
	.S(mult_162_n30));
   FA_X1 mult_162_U22 (.A(mult_162_n35),
	.B(mult_162_n37),
	.CI(mult_162_n30),
	.CO(mult_162_n27),
	.S(mult_162_n28));
   FA_X1 mult_162_U21 (.A(mult_162_n82),
	.B(mult_162_n220),
	.CI(mult_162_n89),
	.CO(mult_162_n25),
	.S(mult_162_n26));
   FA_X1 mult_162_U20 (.A(mult_162_n29),
	.B(mult_162_n76),
	.CI(mult_162_n26),
	.CO(mult_162_n23),
	.S(mult_162_n24));
   FA_X1 mult_162_U18 (.A(mult_162_n213),
	.B(mult_162_n75),
	.CI(mult_162_n25),
	.CO(mult_162_n19),
	.S(mult_162_n20));
   FA_X1 mult_162_U17 (.A(mult_162_n74),
	.B(mult_162_n21),
	.CI(mult_162_n214),
	.CO(mult_162_n17),
	.S(mult_162_n18));
   FA_X1 mult_162_U9 (.A(mult_162_n40),
	.B(mult_162_n45),
	.CI(mult_162_n9),
	.CO(mult_162_n8),
	.S(feedforward[7]));
   FA_X1 mult_162_U8 (.A(mult_162_n34),
	.B(mult_162_n39),
	.CI(mult_162_n8),
	.CO(mult_162_n7),
	.S(feedforward[8]));
   FA_X1 mult_162_U7 (.A(mult_162_n28),
	.B(mult_162_n33),
	.CI(mult_162_n7),
	.CO(mult_162_n6),
	.S(feedforward[9]));
   FA_X1 mult_162_U6 (.A(mult_162_n24),
	.B(mult_162_n27),
	.CI(mult_162_n6),
	.CO(mult_162_n5),
	.S(feedforward[10]));
   FA_X1 mult_162_U5 (.A(mult_162_n20),
	.B(mult_162_n23),
	.CI(mult_162_n5),
	.CO(mult_162_n4),
	.S(feedforward[11]));
   FA_X1 mult_162_U4 (.A(mult_162_n19),
	.B(mult_162_n18),
	.CI(mult_162_n4),
	.CO(mult_162_n3),
	.S(feedforward[12]));
   FA_X1 mult_162_U3 (.A(mult_162_n17),
	.B(mult_162_n208),
	.CI(mult_162_n3),
	.CO(mult_162_n2),
	.S(feedforward[13]));
   FA_X1 mult_162_U2 (.A(mult_162_n209),
	.B(mult_162_n15),
	.CI(mult_162_n2),
	.CO(mult_162_n1),
	.S(feedforward[14]));
   XNOR2_X1 mult_161_U266 (.A(H3[5]),
	.B(FE_OFN1_delayRegOut_1),
	.ZN(mult_161_n282));
   NAND2_X1 mult_161_U265 (.A1(FE_OFN1_delayRegOut_1),
	.A2(FE_DBTN3_delayRegOut_0),
	.ZN(mult_161_n228));
   XNOR2_X1 mult_161_U264 (.A(H3[6]),
	.B(FE_OFN1_delayRegOut_1),
	.ZN(mult_161_n227));
   OAI22_X1 mult_161_U263 (.A1(mult_161_n282),
	.A2(mult_161_n228),
	.B1(mult_161_n227),
	.B2(FE_DBTN3_delayRegOut_0),
	.ZN(mult_161_n100));
   XNOR2_X1 mult_161_U262 (.A(H3[4]),
	.B(FE_OFN1_delayRegOut_1),
	.ZN(mult_161_n281));
   OAI22_X1 mult_161_U261 (.A1(mult_161_n281),
	.A2(mult_161_n228),
	.B1(mult_161_n282),
	.B2(FE_DBTN3_delayRegOut_0),
	.ZN(mult_161_n101));
   XNOR2_X1 mult_161_U260 (.A(H3[3]),
	.B(FE_OFN1_delayRegOut_1),
	.ZN(mult_161_n249));
   OAI22_X1 mult_161_U259 (.A1(mult_161_n249),
	.A2(mult_161_n228),
	.B1(mult_161_n281),
	.B2(FE_DBTN3_delayRegOut_0),
	.ZN(mult_161_n102));
   XOR2_X1 mult_161_U258 (.A(H3[7]),
	.B(FE_DBTN0_delayRegOut_7),
	.Z(mult_161_n270));
   NAND2_X1 mult_161_U256 (.A1(FE_OFN4_mult_161_n262),
	.A2(mult_162_n280),
	.ZN(mult_161_n264));
   XOR2_X1 mult_161_U255 (.A(H3[8]),
	.B(FE_DBTN0_delayRegOut_7),
	.Z(mult_161_n272));
   OAI22_X1 mult_161_U254 (.A1(mult_161_n270),
	.A2(mult_161_n264),
	.B1(FE_OFN4_mult_161_n262),
	.B2(mult_161_n272),
	.ZN(mult_161_n15));
   XOR2_X1 mult_161_U253 (.A(H3[7]),
	.B(FE_DBTN1_delayRegOut_5),
	.Z(mult_161_n259));
   XNOR2_X1 mult_161_U252 (.A(delayRegOut[4]),
	.B(delayRegOut[3]),
	.ZN(mult_161_n251));
   NAND2_X1 mult_161_U250 (.A1(FE_OFN2_mult_161_n251),
	.A2(mult_162_n279),
	.ZN(mult_161_n253));
   XOR2_X1 mult_161_U249 (.A(H3[8]),
	.B(FE_DBTN1_delayRegOut_5),
	.Z(mult_161_n261));
   OAI22_X1 mult_161_U248 (.A1(mult_161_n259),
	.A2(mult_161_n253),
	.B1(FE_OFN2_mult_161_n251),
	.B2(mult_161_n261),
	.ZN(mult_161_n21));
   XOR2_X1 mult_161_U247 (.A(H3[7]),
	.B(delayRegOut[3]),
	.Z(mult_161_n277));
   XNOR2_X1 mult_161_U246 (.A(delayRegOut[2]),
	.B(FE_OFN1_delayRegOut_1),
	.ZN(mult_161_n234));
   XOR2_X1 mult_161_U245 (.A(delayRegOut[3]),
	.B(delayRegOut[2]),
	.Z(mult_161_n278));
   NAND2_X1 mult_161_U244 (.A1(mult_161_n234),
	.A2(mult_161_n278),
	.ZN(mult_161_n233));
   XOR2_X1 mult_161_U243 (.A(H3[8]),
	.B(delayRegOut[3]),
	.Z(mult_161_n250));
   AOI22_X1 mult_161_U242 (.A1(mult_161_n277),
	.A2(mult_161_n221),
	.B1(mult_161_n222),
	.B2(mult_161_n250),
	.ZN(mult_161_n32));
   XOR2_X1 mult_161_U241 (.A(mult_161_n225),
	.B(delayRegOut[7]),
	.Z(mult_161_n265));
   XOR2_X1 mult_161_U240 (.A(H3[3]),
	.B(FE_DBTN0_delayRegOut_7),
	.Z(mult_161_n266));
   OAI22_X1 mult_161_U239 (.A1(mult_161_n265),
	.A2(mult_161_n264),
	.B1(FE_OFN4_mult_161_n262),
	.B2(mult_161_n266),
	.ZN(mult_161_n275));
   XOR2_X1 mult_161_U238 (.A(H3[6]),
	.B(FE_DBTN2_delayRegOut_3),
	.Z(mult_161_n239));
   AOI22_X1 mult_161_U237 (.A1(mult_161_n218),
	.A2(mult_161_n221),
	.B1(mult_161_n222),
	.B2(mult_161_n277),
	.ZN(mult_161_n276));
   NAND2_X1 mult_161_U236 (.A1(mult_161_n207),
	.A2(mult_161_n276),
	.ZN(mult_161_n37));
   XOR2_X1 mult_161_U235 (.A(mult_161_n275),
	.B(mult_161_n276),
	.Z(mult_161_n38));
   OR3_X1 mult_161_U234 (.A1(FE_OFN4_mult_161_n262),
	.A2(H3[1]),
	.A3(FE_DBTN0_delayRegOut_7),
	.ZN(mult_161_n274));
   OAI21_X1 mult_161_U233 (.A(mult_161_n274),
	.B1(FE_DBTN0_delayRegOut_7),
	.B2(mult_161_n264),
	.ZN(mult_161_n69));
   OR3_X1 mult_161_U232 (.A1(FE_OFN2_mult_161_n251),
	.A2(H3[1]),
	.A3(FE_DBTN1_delayRegOut_5),
	.ZN(mult_161_n273));
   OAI21_X1 mult_161_U231 (.A(mult_161_n273),
	.B1(FE_DBTN1_delayRegOut_5),
	.B2(mult_161_n253),
	.ZN(mult_161_n70));
   OAI22_X1 mult_161_U230 (.A1(mult_161_n272),
	.A2(FE_OFN4_mult_161_n262),
	.B1(mult_161_n264),
	.B2(mult_161_n272),
	.ZN(mult_161_n271));
   XOR2_X1 mult_161_U229 (.A(H3[6]),
	.B(FE_DBTN0_delayRegOut_7),
	.Z(mult_161_n269));
   OAI22_X1 mult_161_U228 (.A1(mult_161_n269),
	.A2(mult_161_n264),
	.B1(FE_OFN4_mult_161_n262),
	.B2(mult_161_n270),
	.ZN(mult_161_n74));
   XOR2_X1 mult_161_U227 (.A(H3[5]),
	.B(FE_DBTN0_delayRegOut_7),
	.Z(mult_161_n268));
   OAI22_X1 mult_161_U226 (.A1(mult_161_n268),
	.A2(mult_161_n264),
	.B1(FE_OFN4_mult_161_n262),
	.B2(mult_161_n269),
	.ZN(mult_161_n75));
   XOR2_X1 mult_161_U225 (.A(H3[4]),
	.B(FE_DBTN0_delayRegOut_7),
	.Z(mult_161_n267));
   OAI22_X1 mult_161_U224 (.A1(mult_161_n267),
	.A2(mult_161_n264),
	.B1(FE_OFN4_mult_161_n262),
	.B2(mult_161_n268),
	.ZN(mult_161_n76));
   OAI22_X1 mult_161_U223 (.A1(mult_161_n266),
	.A2(mult_161_n264),
	.B1(FE_OFN4_mult_161_n262),
	.B2(mult_161_n267),
	.ZN(mult_161_n77));
   XOR2_X1 mult_161_U222 (.A(FE_DBTN0_delayRegOut_7),
	.B(H3[1]),
	.Z(mult_161_n263));
   OAI22_X1 mult_161_U221 (.A1(mult_161_n263),
	.A2(mult_161_n264),
	.B1(FE_OFN4_mult_161_n262),
	.B2(mult_161_n265),
	.ZN(mult_161_n79));
   NOR2_X1 mult_161_U220 (.A1(FE_OFN4_mult_161_n262),
	.A2(mult_161_n226),
	.ZN(mult_161_n80));
   OAI22_X1 mult_161_U219 (.A1(mult_161_n261),
	.A2(FE_OFN2_mult_161_n251),
	.B1(mult_161_n253),
	.B2(mult_161_n261),
	.ZN(mult_161_n260));
   XOR2_X1 mult_161_U218 (.A(H3[6]),
	.B(FE_DBTN1_delayRegOut_5),
	.Z(mult_161_n258));
   OAI22_X1 mult_161_U217 (.A1(mult_161_n258),
	.A2(mult_161_n253),
	.B1(FE_OFN2_mult_161_n251),
	.B2(mult_161_n259),
	.ZN(mult_161_n82));
   XOR2_X1 mult_161_U216 (.A(H3[5]),
	.B(FE_DBTN1_delayRegOut_5),
	.Z(mult_161_n257));
   OAI22_X1 mult_161_U215 (.A1(mult_161_n257),
	.A2(mult_161_n253),
	.B1(FE_OFN2_mult_161_n251),
	.B2(mult_161_n258),
	.ZN(mult_161_n83));
   XOR2_X1 mult_161_U214 (.A(H3[4]),
	.B(FE_DBTN1_delayRegOut_5),
	.Z(mult_161_n256));
   OAI22_X1 mult_161_U213 (.A1(mult_161_n256),
	.A2(mult_161_n253),
	.B1(FE_OFN2_mult_161_n251),
	.B2(mult_161_n257),
	.ZN(mult_161_n84));
   XOR2_X1 mult_161_U212 (.A(H3[3]),
	.B(FE_DBTN1_delayRegOut_5),
	.Z(mult_161_n255));
   OAI22_X1 mult_161_U211 (.A1(mult_161_n255),
	.A2(mult_161_n253),
	.B1(FE_OFN2_mult_161_n251),
	.B2(mult_161_n256),
	.ZN(mult_161_n85));
   XOR2_X1 mult_161_U210 (.A(mult_161_n225),
	.B(delayRegOut[5]),
	.Z(mult_161_n254));
   OAI22_X1 mult_161_U209 (.A1(mult_161_n254),
	.A2(mult_161_n253),
	.B1(FE_OFN2_mult_161_n251),
	.B2(mult_161_n255),
	.ZN(mult_161_n86));
   XOR2_X1 mult_161_U208 (.A(mult_161_n226),
	.B(delayRegOut[5]),
	.Z(mult_161_n252));
   OAI22_X1 mult_161_U207 (.A1(mult_161_n252),
	.A2(mult_161_n253),
	.B1(FE_OFN2_mult_161_n251),
	.B2(mult_161_n254),
	.ZN(mult_161_n87));
   NOR2_X1 mult_161_U206 (.A1(FE_OFN2_mult_161_n251),
	.A2(mult_161_n226),
	.ZN(mult_161_n88));
   OAI22_X1 mult_161_U204 (.A1(H3[2]),
	.A2(mult_161_n228),
	.B1(mult_161_n249),
	.B2(FE_DBTN3_delayRegOut_0),
	.ZN(mult_161_n248));
   NAND3_X1 mult_161_U203 (.A1(mult_161_n248),
	.A2(mult_161_n225),
	.A3(FE_OFN1_delayRegOut_1),
	.ZN(mult_161_n246));
   NAND2_X1 mult_161_U202 (.A1(mult_161_n222),
	.A2(mult_161_n248),
	.ZN(mult_161_n247));
   MUX2_X1 mult_161_U201 (.A(mult_161_n246),
	.B(mult_161_n247),
	.S(H3[1]),
	.Z(mult_161_n243));
   NOR3_X1 mult_161_U200 (.A1(mult_161_n234),
	.A2(H3[1]),
	.A3(FE_DBTN2_delayRegOut_3),
	.ZN(mult_161_n245));
   AOI21_X1 mult_161_U199 (.A(mult_161_n245),
	.B1(delayRegOut[3]),
	.B2(mult_161_n221),
	.ZN(mult_161_n244));
   OAI222_X1 mult_161_U198 (.A1(mult_161_n243),
	.A2(mult_161_n217),
	.B1(mult_161_n244),
	.B2(mult_161_n243),
	.C1(mult_161_n244),
	.C2(mult_161_n217),
	.ZN(mult_161_n242));
   AOI222_X1 mult_161_U197 (.A1(mult_161_n242),
	.A2(mult_161_n54),
	.B1(mult_161_n242),
	.B2(mult_161_n55),
	.C1(mult_161_n55),
	.C2(mult_161_n54),
	.ZN(mult_161_n241));
   AOI222_X1 mult_161_U196 (.A1(mult_161_n216),
	.A2(mult_161_n50),
	.B1(mult_161_n216),
	.B2(mult_161_n53),
	.C1(mult_161_n53),
	.C2(mult_161_n50),
	.ZN(mult_161_n240));
   OAI222_X1 mult_161_U195 (.A1(mult_161_n240),
	.A2(mult_161_n211),
	.B1(mult_161_n240),
	.B2(mult_161_n212),
	.C1(mult_161_n212),
	.C2(mult_161_n211),
	.ZN(mult_161_n9));
   XOR2_X1 mult_161_U194 (.A(H3[5]),
	.B(FE_DBTN2_delayRegOut_3),
	.Z(mult_161_n238));
   OAI22_X1 mult_161_U193 (.A1(mult_161_n238),
	.A2(mult_161_n233),
	.B1(mult_161_n234),
	.B2(mult_161_n239),
	.ZN(mult_161_n91));
   XOR2_X1 mult_161_U192 (.A(H3[4]),
	.B(FE_DBTN2_delayRegOut_3),
	.Z(mult_161_n237));
   OAI22_X1 mult_161_U191 (.A1(mult_161_n237),
	.A2(mult_161_n233),
	.B1(mult_161_n234),
	.B2(mult_161_n238),
	.ZN(mult_161_n92));
   XOR2_X1 mult_161_U190 (.A(H3[3]),
	.B(FE_DBTN2_delayRegOut_3),
	.Z(mult_161_n236));
   OAI22_X1 mult_161_U189 (.A1(mult_161_n236),
	.A2(mult_161_n233),
	.B1(mult_161_n234),
	.B2(mult_161_n237),
	.ZN(mult_161_n93));
   XOR2_X1 mult_161_U188 (.A(mult_161_n225),
	.B(delayRegOut[3]),
	.Z(mult_161_n235));
   OAI22_X1 mult_161_U187 (.A1(mult_161_n235),
	.A2(mult_161_n233),
	.B1(mult_161_n234),
	.B2(mult_161_n236),
	.ZN(mult_161_n94));
   XOR2_X1 mult_161_U186 (.A(mult_161_n226),
	.B(delayRegOut[3]),
	.Z(mult_161_n232));
   OAI22_X1 mult_161_U185 (.A1(mult_161_n232),
	.A2(mult_161_n233),
	.B1(mult_161_n234),
	.B2(mult_161_n235),
	.ZN(mult_161_n95));
   XNOR2_X1 mult_161_U184 (.A(H3[8]),
	.B(FE_OFN1_delayRegOut_1),
	.ZN(mult_161_n230));
   XNOR2_X1 mult_161_U182 (.A(H3[7]),
	.B(FE_OFN1_delayRegOut_1),
	.ZN(mult_161_n229));
   OAI22_X1 mult_161_U181 (.A1(mult_161_n229),
	.A2(mult_161_n228),
	.B1(mult_161_n230),
	.B2(FE_DBTN3_delayRegOut_0),
	.ZN(mult_161_n98));
   OAI22_X1 mult_161_U180 (.A1(mult_161_n227),
	.A2(mult_161_n228),
	.B1(mult_161_n229),
	.B2(FE_DBTN3_delayRegOut_0),
	.ZN(mult_161_n99));
   NOR2_X1 mult_161_U179 (.A1(FE_DBTN3_delayRegOut_0),
	.A2(mult_161_n226),
	.ZN(feedback[0]));
   INV_X1 mult_161_U177 (.A(H3[2]),
	.ZN(mult_161_n225));
   INV_X1 mult_161_U176 (.A(H3[1]),
	.ZN(mult_161_n226));
   INV_X1 mult_161_U172 (.A(mult_161_n56),
	.ZN(mult_161_n217));
   XNOR2_X1 mult_161_U171 (.A(delayRegOut[6]),
	.B(delayRegOut[5]),
	.ZN(mult_161_n262));
   INV_X1 mult_161_U170 (.A(mult_161_n260),
	.ZN(mult_161_n214));
   INV_X1 mult_161_U169 (.A(mult_161_n21),
	.ZN(mult_161_n213));
   INV_X1 mult_161_U168 (.A(mult_161_n239),
	.ZN(mult_161_n218));
   INV_X1 mult_161_U167 (.A(mult_161_n32),
	.ZN(mult_161_n220));
   INV_X1 mult_161_U166 (.A(mult_161_n231),
	.ZN(mult_161_n223));
   INV_X1 mult_161_U165 (.A(mult_161_n233),
	.ZN(mult_161_n221));
   INV_X1 mult_161_U164 (.A(mult_161_n271),
	.ZN(mult_161_n209));
   INV_X1 mult_161_U163 (.A(mult_161_n234),
	.ZN(mult_161_n222));
   INV_X1 mult_161_U162 (.A(mult_161_n241),
	.ZN(mult_161_n216));
   INV_X1 mult_161_U161 (.A(mult_161_n1),
	.ZN(feedback[15]));
   INV_X1 mult_161_U160 (.A(mult_161_n15),
	.ZN(mult_161_n208));
   INV_X1 mult_161_U159 (.A(mult_161_n46),
	.ZN(mult_161_n211));
   INV_X1 mult_161_U158 (.A(mult_161_n49),
	.ZN(mult_161_n212));
   INV_X1 mult_161_U157 (.A(mult_161_n275),
	.ZN(mult_161_n207));
   HA_X1 mult_161_U37 (.A(mult_161_n95),
	.B(mult_161_n102),
	.CO(mult_161_n55),
	.S(mult_161_n56));
   FA_X1 mult_161_U36 (.A(mult_161_n101),
	.B(mult_161_n88),
	.CI(mult_161_n94),
	.CO(mult_161_n53),
	.S(mult_161_n54));
   HA_X1 mult_161_U35 (.A(mult_161_n70),
	.B(mult_161_n87),
	.CO(mult_161_n51),
	.S(mult_161_n52));
   FA_X1 mult_161_U34 (.A(mult_161_n93),
	.B(mult_161_n100),
	.CI(mult_161_n52),
	.CO(mult_161_n49),
	.S(mult_161_n50));
   FA_X1 mult_161_U33 (.A(mult_161_n99),
	.B(mult_161_n80),
	.CI(mult_161_n92),
	.CO(mult_161_n47),
	.S(mult_161_n48));
   FA_X1 mult_161_U32 (.A(mult_161_n51),
	.B(mult_161_n86),
	.CI(mult_161_n48),
	.CO(mult_161_n45),
	.S(mult_161_n46));
   HA_X1 mult_161_U31 (.A(mult_161_n69),
	.B(mult_161_n79),
	.CO(mult_161_n43),
	.S(mult_161_n44));
   FA_X1 mult_161_U30 (.A(mult_161_n85),
	.B(mult_161_n98),
	.CI(mult_161_n91),
	.CO(mult_161_n41),
	.S(mult_161_n42));
   FA_X1 mult_161_U29 (.A(mult_161_n47),
	.B(mult_161_n44),
	.CI(mult_161_n42),
	.CO(mult_161_n39),
	.S(mult_161_n40));
   FA_X1 mult_161_U26 (.A(mult_161_n223),
	.B(mult_161_n84),
	.CI(mult_161_n43),
	.CO(mult_161_n35),
	.S(mult_161_n36));
   FA_X1 mult_161_U25 (.A(mult_161_n41),
	.B(mult_161_n38),
	.CI(mult_161_n36),
	.CO(mult_161_n33),
	.S(mult_161_n34));
   FA_X1 mult_161_U23 (.A(mult_161_n77),
	.B(mult_161_n83),
	.CI(mult_161_n32),
	.CO(mult_161_n29),
	.S(mult_161_n30));
   FA_X1 mult_161_U22 (.A(mult_161_n35),
	.B(mult_161_n37),
	.CI(mult_161_n30),
	.CO(mult_161_n27),
	.S(mult_161_n28));
   FA_X1 mult_161_U21 (.A(mult_161_n82),
	.B(mult_161_n220),
	.CI(mult_161_n89),
	.CO(mult_161_n25),
	.S(mult_161_n26));
   FA_X1 mult_161_U20 (.A(mult_161_n29),
	.B(mult_161_n76),
	.CI(mult_161_n26),
	.CO(mult_161_n23),
	.S(mult_161_n24));
   FA_X1 mult_161_U18 (.A(mult_161_n213),
	.B(mult_161_n75),
	.CI(mult_161_n25),
	.CO(mult_161_n19),
	.S(mult_161_n20));
   FA_X1 mult_161_U17 (.A(mult_161_n74),
	.B(mult_161_n21),
	.CI(mult_161_n214),
	.CO(mult_161_n17),
	.S(mult_161_n18));
   FA_X1 mult_161_U9 (.A(mult_161_n40),
	.B(mult_161_n45),
	.CI(mult_161_n9),
	.CO(mult_161_n8),
	.S(feedback[7]));
   FA_X1 mult_161_U8 (.A(mult_161_n34),
	.B(mult_161_n39),
	.CI(mult_161_n8),
	.CO(mult_161_n7),
	.S(feedback[8]));
   FA_X1 mult_161_U7 (.A(mult_161_n28),
	.B(mult_161_n33),
	.CI(mult_161_n7),
	.CO(mult_161_n6),
	.S(feedback[9]));
   FA_X1 mult_161_U6 (.A(mult_161_n24),
	.B(mult_161_n27),
	.CI(mult_161_n6),
	.CO(mult_161_n5),
	.S(feedback[10]));
   FA_X1 mult_161_U5 (.A(mult_161_n20),
	.B(mult_161_n23),
	.CI(mult_161_n5),
	.CO(mult_161_n4),
	.S(feedback[11]));
   FA_X1 mult_161_U4 (.A(mult_161_n19),
	.B(mult_161_n18),
	.CI(mult_161_n4),
	.CO(mult_161_n3),
	.S(feedback[12]));
   FA_X1 mult_161_U3 (.A(mult_161_n17),
	.B(mult_161_n208),
	.CI(mult_161_n3),
	.CO(mult_161_n2),
	.S(feedback[13]));
   FA_X1 mult_161_U2 (.A(mult_161_n209),
	.B(mult_161_n15),
	.CI(mult_161_n2),
	.CO(mult_161_n1),
	.S(feedback[14]));
   XNOR2_X1 mult_172_U266 (.A(H0[5]),
	.B(w_sat[1]),
	.ZN(mult_172_n282));
   NAND2_X1 mult_172_U265 (.A1(w_sat[1]),
	.A2(mult_172_n216),
	.ZN(mult_172_n228));
   XNOR2_X1 mult_172_U264 (.A(H0[6]),
	.B(w_sat[1]),
	.ZN(mult_172_n227));
   OAI22_X1 mult_172_U263 (.A1(mult_172_n282),
	.A2(mult_172_n228),
	.B1(mult_172_n227),
	.B2(mult_172_n216),
	.ZN(mult_172_n100));
   XNOR2_X1 mult_172_U262 (.A(H0[4]),
	.B(w_sat[1]),
	.ZN(mult_172_n281));
   OAI22_X1 mult_172_U261 (.A1(mult_172_n281),
	.A2(mult_172_n228),
	.B1(mult_172_n282),
	.B2(mult_172_n216),
	.ZN(mult_172_n101));
   XNOR2_X1 mult_172_U260 (.A(H0[3]),
	.B(w_sat[1]),
	.ZN(mult_172_n249));
   OAI22_X1 mult_172_U259 (.A1(mult_172_n249),
	.A2(mult_172_n228),
	.B1(mult_172_n281),
	.B2(mult_172_n216),
	.ZN(mult_172_n102));
   XOR2_X1 mult_172_U258 (.A(H0[7]),
	.B(mult_172_n210),
	.Z(mult_172_n270));
   XOR2_X1 mult_172_U257 (.A(w_sat[7]),
	.B(w_sat[6]),
	.Z(mult_172_n280));
   NAND2_X1 mult_172_U256 (.A1(FE_OFN3_mult_172_n262),
	.A2(mult_172_n280),
	.ZN(mult_172_n264));
   XOR2_X1 mult_172_U255 (.A(H0[8]),
	.B(mult_172_n210),
	.Z(mult_172_n272));
   OAI22_X1 mult_172_U254 (.A1(mult_172_n270),
	.A2(mult_172_n264),
	.B1(FE_OFN3_mult_172_n262),
	.B2(mult_172_n272),
	.ZN(mult_172_n15));
   XOR2_X1 mult_172_U253 (.A(H0[7]),
	.B(mult_172_n224),
	.Z(mult_172_n259));
   XOR2_X1 mult_172_U252 (.A(w_sat[5]),
	.B(w_sat[4]),
	.Z(mult_172_n279));
   NAND2_X1 mult_172_U251 (.A1(FE_OFN0_mult_172_n251),
	.A2(mult_172_n279),
	.ZN(mult_172_n253));
   XOR2_X1 mult_172_U250 (.A(H0[8]),
	.B(mult_172_n224),
	.Z(mult_172_n261));
   OAI22_X1 mult_172_U249 (.A1(mult_172_n259),
	.A2(mult_172_n253),
	.B1(FE_OFN0_mult_172_n251),
	.B2(mult_172_n261),
	.ZN(mult_172_n21));
   XOR2_X1 mult_172_U248 (.A(H0[7]),
	.B(w_sat[3]),
	.Z(mult_172_n277));
   XNOR2_X1 mult_172_U247 (.A(w_sat[2]),
	.B(w_sat[1]),
	.ZN(mult_172_n234));
   XOR2_X1 mult_172_U246 (.A(w_sat[3]),
	.B(w_sat[2]),
	.Z(mult_172_n278));
   NAND2_X1 mult_172_U245 (.A1(mult_172_n234),
	.A2(mult_172_n278),
	.ZN(mult_172_n233));
   XOR2_X1 mult_172_U244 (.A(H0[8]),
	.B(w_sat[3]),
	.Z(mult_172_n250));
   AOI22_X1 mult_172_U243 (.A1(mult_172_n277),
	.A2(mult_172_n218),
	.B1(mult_172_n219),
	.B2(mult_172_n250),
	.ZN(mult_172_n32));
   XOR2_X1 mult_172_U242 (.A(mult_172_n225),
	.B(w_sat[7]),
	.Z(mult_172_n265));
   XOR2_X1 mult_172_U241 (.A(H0[3]),
	.B(mult_172_n210),
	.Z(mult_172_n266));
   OAI22_X1 mult_172_U240 (.A1(mult_172_n265),
	.A2(mult_172_n264),
	.B1(FE_OFN3_mult_172_n262),
	.B2(mult_172_n266),
	.ZN(mult_172_n275));
   XOR2_X1 mult_172_U239 (.A(H0[6]),
	.B(mult_172_n221),
	.Z(mult_172_n239));
   AOI22_X1 mult_172_U238 (.A1(mult_172_n220),
	.A2(mult_172_n218),
	.B1(mult_172_n219),
	.B2(mult_172_n277),
	.ZN(mult_172_n276));
   NAND2_X1 mult_172_U237 (.A1(mult_172_n207),
	.A2(mult_172_n276),
	.ZN(mult_172_n37));
   XOR2_X1 mult_172_U236 (.A(mult_172_n275),
	.B(mult_172_n276),
	.Z(mult_172_n38));
   OR3_X1 mult_172_U235 (.A1(FE_OFN3_mult_172_n262),
	.A2(H0[1]),
	.A3(mult_172_n210),
	.ZN(mult_172_n274));
   OAI21_X1 mult_172_U234 (.A(mult_172_n274),
	.B1(mult_172_n210),
	.B2(mult_172_n264),
	.ZN(mult_172_n69));
   OR3_X1 mult_172_U233 (.A1(FE_OFN0_mult_172_n251),
	.A2(H0[1]),
	.A3(mult_172_n224),
	.ZN(mult_172_n273));
   OAI21_X1 mult_172_U232 (.A(mult_172_n273),
	.B1(mult_172_n224),
	.B2(mult_172_n253),
	.ZN(mult_172_n70));
   XOR2_X1 mult_172_U230 (.A(H0[6]),
	.B(mult_172_n210),
	.Z(mult_172_n269));
   OAI22_X1 mult_172_U229 (.A1(mult_172_n269),
	.A2(mult_172_n264),
	.B1(FE_OFN3_mult_172_n262),
	.B2(mult_172_n270),
	.ZN(mult_172_n74));
   XOR2_X1 mult_172_U228 (.A(H0[5]),
	.B(mult_172_n210),
	.Z(mult_172_n268));
   OAI22_X1 mult_172_U227 (.A1(mult_172_n268),
	.A2(mult_172_n264),
	.B1(FE_OFN3_mult_172_n262),
	.B2(mult_172_n269),
	.ZN(mult_172_n75));
   XOR2_X1 mult_172_U226 (.A(H0[4]),
	.B(mult_172_n210),
	.Z(mult_172_n267));
   OAI22_X1 mult_172_U225 (.A1(mult_172_n267),
	.A2(mult_172_n264),
	.B1(FE_OFN3_mult_172_n262),
	.B2(mult_172_n268),
	.ZN(mult_172_n76));
   OAI22_X1 mult_172_U224 (.A1(mult_172_n266),
	.A2(mult_172_n264),
	.B1(FE_OFN3_mult_172_n262),
	.B2(mult_172_n267),
	.ZN(mult_172_n77));
   XOR2_X1 mult_172_U223 (.A(mult_172_n210),
	.B(H0[1]),
	.Z(mult_172_n263));
   OAI22_X1 mult_172_U222 (.A1(mult_172_n263),
	.A2(mult_172_n264),
	.B1(FE_OFN3_mult_172_n262),
	.B2(mult_172_n265),
	.ZN(mult_172_n79));
   NOR2_X1 mult_172_U221 (.A1(FE_OFN3_mult_172_n262),
	.A2(mult_172_n226),
	.ZN(mult_172_n80));
   XOR2_X1 mult_172_U219 (.A(H0[6]),
	.B(mult_172_n224),
	.Z(mult_172_n258));
   OAI22_X1 mult_172_U218 (.A1(mult_172_n258),
	.A2(mult_172_n253),
	.B1(FE_OFN0_mult_172_n251),
	.B2(mult_172_n259),
	.ZN(mult_172_n82));
   XOR2_X1 mult_172_U217 (.A(H0[5]),
	.B(mult_172_n224),
	.Z(mult_172_n257));
   OAI22_X1 mult_172_U216 (.A1(mult_172_n257),
	.A2(mult_172_n253),
	.B1(FE_OFN0_mult_172_n251),
	.B2(mult_172_n258),
	.ZN(mult_172_n83));
   XOR2_X1 mult_172_U215 (.A(H0[4]),
	.B(mult_172_n224),
	.Z(mult_172_n256));
   OAI22_X1 mult_172_U214 (.A1(mult_172_n256),
	.A2(mult_172_n253),
	.B1(FE_OFN0_mult_172_n251),
	.B2(mult_172_n257),
	.ZN(mult_172_n84));
   XOR2_X1 mult_172_U213 (.A(H0[3]),
	.B(mult_172_n224),
	.Z(mult_172_n255));
   OAI22_X1 mult_172_U212 (.A1(mult_172_n255),
	.A2(mult_172_n253),
	.B1(FE_OFN0_mult_172_n251),
	.B2(mult_172_n256),
	.ZN(mult_172_n85));
   XOR2_X1 mult_172_U211 (.A(mult_172_n225),
	.B(w_sat[5]),
	.Z(mult_172_n254));
   OAI22_X1 mult_172_U210 (.A1(mult_172_n254),
	.A2(mult_172_n253),
	.B1(FE_OFN0_mult_172_n251),
	.B2(mult_172_n255),
	.ZN(mult_172_n86));
   XOR2_X1 mult_172_U209 (.A(mult_172_n226),
	.B(w_sat[5]),
	.Z(mult_172_n252));
   OAI22_X1 mult_172_U208 (.A1(mult_172_n252),
	.A2(mult_172_n253),
	.B1(FE_OFN0_mult_172_n251),
	.B2(mult_172_n254),
	.ZN(mult_172_n87));
   NOR2_X1 mult_172_U207 (.A1(FE_OFN0_mult_172_n251),
	.A2(mult_172_n226),
	.ZN(mult_172_n88));
   OAI22_X1 mult_172_U205 (.A1(H0[2]),
	.A2(mult_172_n228),
	.B1(mult_172_n249),
	.B2(mult_172_n216),
	.ZN(mult_172_n248));
   NAND3_X1 mult_172_U204 (.A1(mult_172_n248),
	.A2(mult_172_n225),
	.A3(w_sat[1]),
	.ZN(mult_172_n246));
   NAND2_X1 mult_172_U203 (.A1(mult_172_n219),
	.A2(mult_172_n248),
	.ZN(mult_172_n247));
   MUX2_X1 mult_172_U202 (.A(mult_172_n246),
	.B(mult_172_n247),
	.S(H0[1]),
	.Z(mult_172_n243));
   NOR3_X1 mult_172_U201 (.A1(mult_172_n234),
	.A2(H0[1]),
	.A3(mult_172_n221),
	.ZN(mult_172_n245));
   AOI21_X1 mult_172_U200 (.A(mult_172_n245),
	.B1(w_sat[3]),
	.B2(mult_172_n218),
	.ZN(mult_172_n244));
   OAI222_X1 mult_172_U199 (.A1(mult_172_n243),
	.A2(mult_172_n213),
	.B1(mult_172_n244),
	.B2(mult_172_n243),
	.C1(mult_172_n244),
	.C2(mult_172_n213),
	.ZN(mult_172_n242));
   AOI222_X1 mult_172_U198 (.A1(mult_172_n242),
	.A2(mult_172_n54),
	.B1(mult_172_n242),
	.B2(mult_172_n55),
	.C1(mult_172_n55),
	.C2(mult_172_n54),
	.ZN(mult_172_n241));
   AOI222_X1 mult_172_U197 (.A1(mult_172_n212),
	.A2(mult_172_n50),
	.B1(mult_172_n212),
	.B2(mult_172_n53),
	.C1(mult_172_n53),
	.C2(mult_172_n50),
	.ZN(mult_172_n240));
   OAI222_X1 mult_172_U196 (.A1(mult_172_n240),
	.A2(mult_172_n215),
	.B1(mult_172_n240),
	.B2(mult_172_n211),
	.C1(mult_172_n211),
	.C2(mult_172_n215),
	.ZN(mult_172_n9));
   XOR2_X1 mult_172_U195 (.A(H0[5]),
	.B(mult_172_n221),
	.Z(mult_172_n238));
   OAI22_X1 mult_172_U194 (.A1(mult_172_n238),
	.A2(mult_172_n233),
	.B1(mult_172_n234),
	.B2(mult_172_n239),
	.ZN(mult_172_n91));
   XOR2_X1 mult_172_U193 (.A(H0[4]),
	.B(mult_172_n221),
	.Z(mult_172_n237));
   OAI22_X1 mult_172_U192 (.A1(mult_172_n237),
	.A2(mult_172_n233),
	.B1(mult_172_n234),
	.B2(mult_172_n238),
	.ZN(mult_172_n92));
   XOR2_X1 mult_172_U191 (.A(H0[3]),
	.B(mult_172_n221),
	.Z(mult_172_n236));
   OAI22_X1 mult_172_U190 (.A1(mult_172_n236),
	.A2(mult_172_n233),
	.B1(mult_172_n234),
	.B2(mult_172_n237),
	.ZN(mult_172_n93));
   XOR2_X1 mult_172_U189 (.A(mult_172_n225),
	.B(w_sat[3]),
	.Z(mult_172_n235));
   OAI22_X1 mult_172_U188 (.A1(mult_172_n235),
	.A2(mult_172_n233),
	.B1(mult_172_n234),
	.B2(mult_172_n236),
	.ZN(mult_172_n94));
   XOR2_X1 mult_172_U187 (.A(mult_172_n226),
	.B(w_sat[3]),
	.Z(mult_172_n232));
   OAI22_X1 mult_172_U186 (.A1(mult_172_n232),
	.A2(mult_172_n233),
	.B1(mult_172_n234),
	.B2(mult_172_n235),
	.ZN(mult_172_n95));
   XNOR2_X1 mult_172_U185 (.A(H0[8]),
	.B(w_sat[1]),
	.ZN(mult_172_n230));
   XNOR2_X1 mult_172_U183 (.A(H0[7]),
	.B(w_sat[1]),
	.ZN(mult_172_n229));
   OAI22_X1 mult_172_U182 (.A1(mult_172_n229),
	.A2(mult_172_n228),
	.B1(mult_172_n230),
	.B2(mult_172_n216),
	.ZN(mult_172_n98));
   OAI22_X1 mult_172_U181 (.A1(mult_172_n227),
	.A2(mult_172_n228),
	.B1(mult_172_n229),
	.B2(mult_172_n216),
	.ZN(mult_172_n99));
   NOR2_X1 mult_172_U180 (.A1(mult_172_n216),
	.A2(mult_172_n226),
	.ZN(multb0[0]));
   INV_X1 mult_172_U179 (.A(H0[2]),
	.ZN(mult_172_n225));
   INV_X1 mult_172_U178 (.A(H0[1]),
	.ZN(mult_172_n226));
   INV_X1 mult_172_U177 (.A(mult_172_n56),
	.ZN(mult_172_n213));
   INV_X1 mult_172_U176 (.A(mult_172_n260),
	.ZN(mult_172_n223));
   INV_X1 mult_172_U175 (.A(mult_172_n21),
	.ZN(mult_172_n222));
   INV_X1 mult_172_U174 (.A(mult_172_n32),
	.ZN(mult_172_n217));
   INV_X1 mult_172_U173 (.A(mult_172_n231),
	.ZN(mult_172_n214));
   INV_X1 mult_172_U172 (.A(mult_172_n271),
	.ZN(mult_172_n209));
   INV_X1 mult_172_U171 (.A(w_sat[0]),
	.ZN(mult_172_n216));
   INV_X1 mult_172_U170 (.A(w_sat[7]),
	.ZN(mult_172_n210));
   INV_X1 mult_172_U169 (.A(mult_172_n239),
	.ZN(mult_172_n220));
   INV_X1 mult_172_U168 (.A(mult_172_n241),
	.ZN(mult_172_n212));
   INV_X1 mult_172_U167 (.A(mult_172_n1),
	.ZN(multb0[15]));
   INV_X1 mult_172_U166 (.A(mult_172_n15),
	.ZN(mult_172_n208));
   INV_X1 mult_172_U165 (.A(mult_172_n46),
	.ZN(mult_172_n215));
   INV_X1 mult_172_U164 (.A(mult_172_n49),
	.ZN(mult_172_n211));
   INV_X1 mult_172_U163 (.A(mult_172_n275),
	.ZN(mult_172_n207));
   INV_X1 mult_172_U162 (.A(w_sat[3]),
	.ZN(mult_172_n221));
   INV_X1 mult_172_U161 (.A(w_sat[5]),
	.ZN(mult_172_n224));
   XNOR2_X1 mult_172_U160 (.A(w_sat[6]),
	.B(w_sat[5]),
	.ZN(mult_172_n262));
   XNOR2_X1 mult_172_U159 (.A(w_sat[4]),
	.B(w_sat[3]),
	.ZN(mult_172_n251));
   INV_X1 mult_172_U158 (.A(mult_172_n233),
	.ZN(mult_172_n218));
   INV_X1 mult_172_U157 (.A(mult_172_n234),
	.ZN(mult_172_n219));
   HA_X1 mult_172_U37 (.A(mult_172_n95),
	.B(mult_172_n102),
	.CO(mult_172_n55),
	.S(mult_172_n56));
   FA_X1 mult_172_U36 (.A(mult_172_n101),
	.B(mult_172_n88),
	.CI(mult_172_n94),
	.CO(mult_172_n53),
	.S(mult_172_n54));
   HA_X1 mult_172_U35 (.A(mult_172_n70),
	.B(mult_172_n87),
	.CO(mult_172_n51),
	.S(mult_172_n52));
   FA_X1 mult_172_U34 (.A(mult_172_n93),
	.B(mult_172_n100),
	.CI(mult_172_n52),
	.CO(mult_172_n49),
	.S(mult_172_n50));
   FA_X1 mult_172_U33 (.A(mult_172_n99),
	.B(mult_172_n80),
	.CI(mult_172_n92),
	.CO(mult_172_n47),
	.S(mult_172_n48));
   FA_X1 mult_172_U32 (.A(mult_172_n51),
	.B(mult_172_n86),
	.CI(mult_172_n48),
	.CO(mult_172_n45),
	.S(mult_172_n46));
   HA_X1 mult_172_U31 (.A(mult_172_n69),
	.B(mult_172_n79),
	.CO(mult_172_n43),
	.S(mult_172_n44));
   FA_X1 mult_172_U30 (.A(mult_172_n85),
	.B(mult_172_n98),
	.CI(mult_172_n91),
	.CO(mult_172_n41),
	.S(mult_172_n42));
   FA_X1 mult_172_U29 (.A(mult_172_n47),
	.B(mult_172_n44),
	.CI(mult_172_n42),
	.CO(mult_172_n39),
	.S(mult_172_n40));
   FA_X1 mult_172_U26 (.A(mult_172_n214),
	.B(mult_172_n84),
	.CI(mult_172_n43),
	.CO(mult_172_n35),
	.S(mult_172_n36));
   FA_X1 mult_172_U25 (.A(mult_172_n41),
	.B(mult_172_n38),
	.CI(mult_172_n36),
	.CO(mult_172_n33),
	.S(mult_172_n34));
   FA_X1 mult_172_U23 (.A(mult_172_n77),
	.B(mult_172_n83),
	.CI(mult_172_n32),
	.CO(mult_172_n29),
	.S(mult_172_n30));
   FA_X1 mult_172_U22 (.A(mult_172_n35),
	.B(mult_172_n37),
	.CI(mult_172_n30),
	.CO(mult_172_n27),
	.S(mult_172_n28));
   FA_X1 mult_172_U21 (.A(mult_172_n82),
	.B(mult_172_n217),
	.CI(mult_172_n89),
	.CO(mult_172_n25),
	.S(mult_172_n26));
   FA_X1 mult_172_U20 (.A(mult_172_n29),
	.B(mult_172_n76),
	.CI(mult_172_n26),
	.CO(mult_172_n23),
	.S(mult_172_n24));
   FA_X1 mult_172_U18 (.A(mult_172_n222),
	.B(mult_172_n75),
	.CI(mult_172_n25),
	.CO(mult_172_n19),
	.S(mult_172_n20));
   FA_X1 mult_172_U17 (.A(mult_172_n74),
	.B(mult_172_n21),
	.CI(mult_172_n223),
	.CO(mult_172_n17),
	.S(mult_172_n18));
   FA_X1 mult_172_U9 (.A(mult_172_n40),
	.B(mult_172_n45),
	.CI(mult_172_n9),
	.CO(mult_172_n8),
	.S(multb0[7]));
   FA_X1 mult_172_U8 (.A(mult_172_n34),
	.B(mult_172_n39),
	.CI(mult_172_n8),
	.CO(mult_172_n7),
	.S(multb0[8]));
   FA_X1 mult_172_U7 (.A(mult_172_n28),
	.B(mult_172_n33),
	.CI(mult_172_n7),
	.CO(mult_172_n6),
	.S(multb0[9]));
   FA_X1 mult_172_U6 (.A(mult_172_n24),
	.B(mult_172_n27),
	.CI(mult_172_n6),
	.CO(mult_172_n5),
	.S(multb0[10]));
   FA_X1 mult_172_U5 (.A(mult_172_n20),
	.B(mult_172_n23),
	.CI(mult_172_n5),
	.CO(mult_172_n4),
	.S(multb0[11]));
   FA_X1 mult_172_U4 (.A(mult_172_n19),
	.B(mult_172_n18),
	.CI(mult_172_n4),
	.CO(mult_172_n3),
	.S(multb0[12]));
   FA_X1 mult_172_U3 (.A(mult_172_n17),
	.B(mult_172_n208),
	.CI(mult_172_n3),
	.CO(mult_172_n2),
	.S(multb0[13]));
   FA_X1 mult_172_U2 (.A(mult_172_n209),
	.B(mult_172_n15),
	.CI(mult_172_n2),
	.CO(mult_172_n1),
	.S(multb0[14]));
endmodule

